### ISSUE TITLE
support for python 3 

### ISSUE THREAD

**Issue by thisisrrs** [HewlettPackard/python-ilorest-library#10]
The  original redfish repo ( DMTF/python-redfish-library) got recentlu updated to support latest 3.x
Can you please make this compatible 

Thanks in Advance

**Comment by Yergidy** [comment]
@thisisrrs The next release of the library will have installers with support. The source should already be compatible.

**Comment by Yergidy** [comment]
We have released version 2.1 which includes full python 3 compatibility. A pip version will follow in the coming days.

**Comment by Yergidy** [comment]
a pip version is now available for version 2.1
