### ISSUE TITLE
add_user_account.py example does not set the password

### ISSUE THREAD

**Issue by toribio-rch** [HewlettPackard/python-ilorest-library#102]
Hello,

I am trying to get a user created in an iLO 5 and I used the example provided here. Everything works fine but the password. The user is created and privileges are set properly. But When I try to enter with the password provided, I cannot log in. The output of the Python script gives all the details in JSON format and password value is "null". I do not know if the value is really null or maybe it is hidden, but the fact is that I cannot login with the user recently created. I checked the value of the variable before and after the user creation and seems to be fine, but the password is not correctly set.

Specifically, I think the error could be when doing the post method to add the user:

**resp = _redfishobj.post(account_collection_uri, body)**

Python version is 3.9

Script JSON output (latest lines):
    },
    **"Password": null,**
    "PasswordChangeRequired": false,
    "RoleId": "Administrator",
    "UserName": "Antonio Toribio"
}

JSON body built before executing the post:

{'Oem': {'Hpe': {'LoginName': 'antonio',
                 'Privileges': {'HostBIOSConfigPriv': True,
                                'HostNICConfigPriv': True,
                                'HostStorageConfigPriv': True,
                                'LoginPriv': True,
                                'RemoteConsolePriv': True,
                                'SystemRecoveryConfigPriv': True,
                                'UserConfigPriv': True,
                                'VirtualMediaPriv': True,
                                'VirtualPowerAndResetPriv': True,
                                'iLOConfigPriv': True}}},
 **'Password': 'engineering',**
 'UserName': 'Antonio Toribio'}

Could you please help me to figure out what is not working to set the password?
Thanks,

**Comment by samiron7567** [comment]
Just use below in your payload. Should be fine. I have that tested many times.

The RestAPI url `"/redfish/v1/AccountService/Accounts/"`
```
{
    "Password": "test1231234",
    "RoleId": "Administrator",
    "UserName": "root"
}
```

**Comment by rajeevkallur** [comment]
Please use the script 
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/add_user_account.py
