### ISSUE TITLE
Unable to setup SmartArray EncryptionSettings

### ISSUE THREAD

**Issue by samiron7567** [HewlettPackard/python-ilorest-library#103]
With reference to the below get_SmartArray_EncryptionSettings and with the HPE RestAPI reference guide, I am unable to find parameters to setup encryption using RestAPI. Please provide one or make the documentation available as referance.

[https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/get_SmartArray_EncryptionSettings.py](https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/get_SmartArray_EncryptionSettings.py)

I understand these are the desired properties to get values but with help of these I would like to set `"CryptoOfficerPassword, MasterKey, CryptoOfficerRecoveryQuestion/Answer"` as well. Please help!

```
"EncryptionBootPasswordSet"
"EncryptionCryptoOfficerPasswordSet"
"EncryptionLocalKeyCacheEnabled"
"EncryptionMixedVolumesEnabled"
"EncryptionPhysicalDriveCount"
"EncryptionRecoveryParamsSet"
"EncryptionStandaloneModeEnabled"
"EncryptionUserPasswordSet"
```

**Comment by samiron7567** [comment]
Looks like there is no POST or PATCH method available in `/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/` If anyone knows the exact link to setup encryption, that woule be very much helpful

```
{
        "@odata.id": "/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/",
        "@odata.type": "#HpeSmartStorageArrayController.v2_2_0.HpeSmartStorageArrayController",
        "ETag": "W/\"8B667AD8\"",
        "HttpMethods": [
            "GET",
            "HEAD"
        ]
}
```

**Comment by rajeevkallur** [comment]
Please check /redfish/v1/Systems/1/SmartStorageConfig URI which has POST/PATCH available.
