### ISSUE TITLE
pypi.org credentials exposed in .travis.yml

### ISSUE THREAD

**Issue by martin-schlossarek** [HewlettPackard/python-ilorest-library#107]
As the title suggests, your pypi.org credentials are compromised: 

https://github.com/HewlettPackard/python-ilorest-library/blob/344a52e55a1fdf5807461fcc5b7cb8f2cd13c386/.travis.yml#L15-L17

Anyone can release new versions with malicious code in HPE's name. 

Please fix this.

**Comment by rajeevkallur** [comment]
.travis.yml file is now deleted from the repository.
