### ISSUE TITLE
Change Bios Attributes doesn't work with example ex03_change_bios_setting.py

### ISSUE THREAD

**Issue by phcoquard** [HewlettPackard/python-ilorest-library#11]
The "ex03_change_bios_setting.py"  Redfish example doesn't work with HPE Proliant DL380 gen10 model for updading Bios attributes
I needed to change "body = {bios_property: property_value}" to "body = {"Attributes": {bios_property: property_value}}" otherwise the PATCH request doesn't commit the change.
When using body = {bios_property: property_value} , the PATCH request is done  with no error but the value is not changed even after reset.

I don't known if this behavior is normal or not
Thank's

**Comment by Yergidy** [comment]
@phcoquard Thank you. Yes, this is not normal behavior. We will update the body to the correct form.

**Comment by Yergidy** [comment]
#12 should fix this issue.
