### ISSUE TITLE
Inband connection failure on Gen10 servers

### ISSUE THREAD

**Issue by UndyingScroll** [HewlettPackard/python-ilorest-library#111]
#### Description
Running inband (blobstore) communications fails to connect to a Gen10 Proliant server(iLO5 2.10 Oct 30 2019) with the 3.2.1 release. 
Inband communication succeeds with 3.2.1 against a Gen9 Proliant server(iLO 4 2.74 May 08 2020). 
Gen9 and Gen10 inband communication succeeds with 3.1.1 release against the same machines.

#### To Reproduce

Modify quickstart_redfish.py to run with blobstore (SYSTEM_URL = "blobstore://." , LOGIN_ACCOUNT = "None", LOGIN_PASSWORD = "None")

Returns:
 raising:
    raise InvalidCredentialsError(0)
redfish.rest.connections.InvalidCredentialsError: 0

It appears that dll.ChifVerifyCredentials() is returning a value of 5.

**Comment by UndyingScroll** [comment]
I see it now; username should be None and not 'None'.

**Comment by rajeevkallur** [comment]
Please let us know if it is still issue. Btw, there is new version 3.2.2 released!!
