### ISSUE TITLE
Base.1.0.PropertyMissing when setting bios password

### ISSUE THREAD

**Issue by mpictor** [HewlettPackard/python-ilorest-library#115]
```console
$ ilorest setpassword --url https://1.2.3.4 -u user -p pass --currentpassword hunter2 --newpassword None --verbose --includelogs
iLOrest : RESTful Interface Tool version 3.2.2
Copyright (c) 2014-2021 Hewlett Packard Enterprise Development LP
-------------------------------------------------------------------------------------------------------------------------
Discovering data...Done
[400] Base.1.0.PropertyMissing
ILOREST return code: 63
```

Product Name `ProLiant DL360 Gen10`
iLO Firmware Version `1.45 Jun 27 2019`
System ROM `U32 v2.14 (09/05/2019)`

Using `iLOrest : RESTful Interface Tool version 2.1`, the equivalent command (`ilorest setpassword --url https://1.2.3.4 -u user -p pass '' hunter2`) succeeds on the same machine.

**Comment by JohnAZoidberg** [comment]
The code for the `ilorest` command is here: https://github.com/HewlettPackard/python-redfish-utility
Please submit your issue there.

**Comment by rajeevkallur** [comment]
This was fixed in later iLO versions. Please iLO FW > 2.40
