### ISSUE TITLE
ModuleNotFoundError: No module named 'get_resource_directory'

### ISSUE THREAD

**Issue by smutel** [HewlettPackard/python-ilorest-library#116]
Hello,

I would like to use the ilorest library with ansible.
I tried to setup the timezone with the `set_ilo_timezone`module.
However I received the message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'get_resource_directory'
fatal: [xxx]: FAILED! => changed=false
```

I already installed:
```
python-ilorest-library 3.2.2
```

What do you need to install in addition ?

**Comment by rajeevkallur** [comment]
You can copy this and rerun.
https://github.com/HewlettPackard/ansible-ilorest-role/blob/master/library/get_resource_directory.py
