### ISSUE TITLE
The prefix of ip cause the auth failure. 

### ISSUE THREAD

**Issue by unequaled** [HewlettPackard/python-ilorest-library#119]
I gave the URL without the prefix "https" which causes the problem during the auth. Once add the prefix by myself. There is not problem at all.
![image](https://user-images.githubusercontent.com/6347649/139773409-0aa6a311-0f26-43f5-b558-7f7d715c1ed8.png)

**Comment by kaviyajm** [comment]
Hi @unequaled, 

what is ams_rest.py, can you please share the script

**Comment by rajeevkallur** [comment]
This is fixed
