### ISSUE TITLE
Is there a way to get the console screenshot?

### ISSUE THREAD

**Issue by sultanofswag** [HewlettPackard/python-ilorest-library#121]
Similar to Dell iDRAC?

**Comment by rajeevkallur** [comment]
You open console and click on camera icon to get console screenshot.  iLO also has screenrecording feature as well with iLO Standalone client.

![image](https://user-images.githubusercontent.com/21117913/141077127-5830d010-764b-4f01-8763-597b41885e31.png)

**Comment by sultanofswag** [comment]
Sorry. I meant "is there a way to get the console screenshot programmatically", so I can script it (linux) and run it through a image to text module to automate (or semi-automate) certain setup tasks.

I could do that for dell using the Redfish API scripts but cannot figure it out for HP iLO 5. We have a few hundred HP (DL 380 Gen 10) servers to setup with a custom OS. Being able to automate this will be very helpful.

Another part to this is being able to wake up the console if it times out and goes to sleep (if this prevents taking a console screenshot). Again, was able to do that for non-HP servers by sending a keystroke through a VNC server build into the remote management module (not very clean but there was no way to do it through the redfish api or other native mechanisms).

Thank you for the quick response.

**Comment by rajeevkallur** [comment]
@sultanofswag ,  Can you try a GET on the URL https://<ILOIP>/images/thumbnail.bmp and save the response to bmp or jpeg file?

![image](https://user-images.githubusercontent.com/21117913/166202798-4295f234-a4a8-44b5-922f-6c71c88db2e5.png)

**Comment by kaviyajm** [comment]
@sultanofswag can you please try this ,
curl --header "Accept: */*" --header "Accept-Encoding: gzip, deflate, br" -u username:password --insecure --output thumbnailCurl.bmp https://<ip>/images/thumbnail.bmp

**Comment by rajeevkallur** [comment]
Above command should work fine.  Please reopen if otherwise.
