### ISSUE TITLE
Is there a virtual media eject script?

### ISSUE THREAD

**Issue by sultanofswag** [HewlettPackard/python-ilorest-library#122]
Or, what do I change in the mount script (mount_virtual_media_iso.py) to make it eject the media?

Thank you

**Comment by kaviyajm** [comment]
Hi @sultanofswag 
please find the below link for virtual media eject
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/eject_virtual_media_iso.py
