### ISSUE TITLE
Is there an Update Recovery Set option for firmware file upload to iLO repo using the HTTP PUSH URI

### ISSUE THREAD

**Issue by nathanlin24** [HewlettPackard/python-ilorest-library#124]
Hello,

I see with iLO5 version 2.48 on Moonshot m710 there is a option to update the recovery set at firmware upload. What is the name of the parameter to do this?

Please see the image snippet below the update recover set option that shows on m710 blade system. What is the parameter we can set to enable it at firmware upload?

![image](https://user-images.githubusercontent.com/46579276/152042384-f28af565-5d41-4a58-b66f-39e5f18e01ff.png)

Thanks.

**Comment by rajeevkallur** [comment]
Please refer https://hewlettpackard.github.io/python-redfish-utility/#uploadcomp-command

option is --update_srs

**Comment by nathanlin24** [comment]
Thank you. What about if I'm calling the iLO Redfish API directly in a script? Is there a parameter I can set in the POST request body for "Update Recovery Set"? Thanks.

**Comment by kaviyajm** [comment]
**POST:** https://{IP}/redfish/v1/UpdateService/Actions/Oem/Hpe/HpeiLOUpdateServiceExt.AddFromUri/

**BODY:**
 {
    "ImageURI":"http://{webserver IP}/ilo_build/ilo5_263_p07.bin",    
    "UpdateTarget":false,
    "UpdateRepository":true,
    "UpdateRecoverySet":true
 }
