### ISSUE TITLE
Advanced-Usage.rest contains conflict markers

### ISSUE THREAD

**Issue by dimkup** [HewlettPackard/python-ilorest-library#125]
Lines 146, 178 of [Advanced-Usage.rest](https://github.com/HewlettPackard/python-ilorest-library/blob/245a0c134e6dec4188abd0cecdfde8fce84d2d0d/docs/Advanced-Usage.rest) contain <<<<<<< and >>>>>>> which prevents some version control systems from working correctly..

**Comment by kaviyajm** [comment]
Hi, we will update the [Advanced-Usage.rest](https://github.com/HewlettPackard/python-ilorest-library/blob/245a0c134e6dec4188abd0cecdfde8fce84d2d0d/docs/Advanced-Usage.rest) will keep you posted once changes are done

**Comment by rajeevkallur** [comment]
Fixed
