### ISSUE TITLE
Feature Request - Support OneView SSO

### ISSUE THREAD

**Issue by mcrossley** [HewlettPackard/python-ilorest-library#126]
It would be great if the Windows utility would accept an X-Auth-Token for authentication credentials.

Then you can use the OneView iLO Single-Sign-On facility to launch the tools without having to pass clear text passwords.

**Comment by kaviyajm** [comment]
Hi @mcrossley 
As of now this request is not supported in iLORest,
we will discuss with Engineering team to take this request as an enhancement for the next release.

**Comment by rajeevkallur** [comment]
we will address this next release
