### ISSUE TITLE
Boot to RBSU with ilorest? RAID 1 not detected in bootorder.

### ISSUE THREAD

**Issue by ralfgro** [HewlettPackard/python-ilorest-library#128]
After creating a RAID 1 with ilorest tool followed by a cold boot, the newly created RAID 1 was not shown in boot order settings. The ILO GUI showed the RAID 1 under Storage, as well as ilorest tool did. I rebooted (cold) the server multiple times. This happend only once now before my Ansible workflow with ilorest command was always successful. The script checks for the existence of RAID 1 and moves it to #3 of bootorder.

Anyhow,  booting the server with F11 into boot menu showed the RAID 1 device. ILO GUI and ilorest tool also showed the device afterwards and I could change the boot order then with my script.

Is there any command I can/should issue after creating a RAID 1 so that it is detected? Other than a reboot/reset? As pressing F11 did the trick, I would like to add this or entering RBSU followed by a reset to my script. Is this possible with ilorest command?

**Comment by kaviyajm** [comment]
Hi @ralfgro ,

May I know, which controller you created?

**Comment by kaviyajm** [comment]
Hi @ralfgro,

you should do a reboot/reset to see the newly created RAID. iLORest have a command to do reboot,
**Command** : ilorest -v reboot

**Comment by rajeevkallur** [comment]
@ralfgro ,  For simulating F11, you could do ilorest -v bootorder --onetimeboot=BiosSetup --commit --reboot
Please refer:
https://hewlettpackard.github.io/python-redfish-utility/#bootorder-command
