### ISSUE TITLE
Unable to change UEFI boot settings

### ISSUE THREAD

**Issue by thk4711** [HewlettPackard/python-ilorest-library#13]
I am trying to change the UEFI boot order with the code from example  07. But I am getting the following:

EXAMPLE 7: Change Boot Order (UEFI)
	'ServerBootSettings.' resource or feature is not supported on this system

Other examples are working .

My system is a DL380G9 .

**Comment by Yergidy** [comment]
@thk4711 Thanks. We will take a look at this issue.

**Comment by Yergidy** [comment]
@thk4711 Sorry for the late response. This is due to bios types not being redfish conformant until G10. Using the rest example counterpart of this should work correctly.
