### ISSUE TITLE
Can I send a "testevent" using ilorest?

### ISSUE THREAD

**Issue by znop-sf** [HewlettPackard/python-ilorest-library#131]

**Comment by rajeevkallur** [comment]
You can check sendtest command for ilorest and also following scripts
https://github.com/HewlettPackard/python-redfish-utility/blob/master/examples/Windows/Send_Snmp_Test_Trap.bat
https://github.com/HewlettPackard/python-redfish-utility/blob/master/examples/Linux/Send_Snmp_Test_Trap.sh

**Comment by znop-sf** [comment]
Thanks a lot @rajeevkallur, I saw these commands. I'm after this I think - which does not have ilorest equivalent as far as I know? 
https://support.hpe.com/hpesc/public/docDisplay?docId=a00118967en_us&docLocale=en_US&page=GUID-EE3CD033-D78A-4D47-B7AF-E1411F207893.html

**Comment by rajeevkallur** [comment]
ohh.  I dont think that is provided in ilorest tool.  We can provide a shell script which can directly work in iLO as in the link you provided.
