### ISSUE TITLE
iLOREST presumes /tmp has execute privilege

### ISSUE THREAD

**Issue by SenseiC** [HewlettPackard/python-ilorest-library#14]
1.	Install iLOREST
2.	Confirm iLOREST runs
3.	Remount /tmp without exec privilege
4.	Confirm iLOREST no longer runs
5.	Create a new "temp" directory
6.	Define an environment variable TMP (or TMPDIR) with that new "temp" directory
7.	Confirm iLOREST now executes properly

[root@ml150g9d39u12l ~]# grep PRETTY /etc/os-release
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
[root@ml150g9d39u12l ~]# rpm -ivh /FileUpload/jpcustin/ilorest-2.1-73.x86_64.rpm                                                                 
warning: /FileUpload/jpcustin/ilorest-2.1-73.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 26c2b797: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:ilorest-2.1-73                   ################################# [100%]
[root@ml150g9d39u12l ~]# ilorest
iLOrest : RESTful Interface Tool version 2.1
Copyright (c) 2014, 2017 Hewlett Packard Enterprise Development Company
-------------------------------------------------------------------------------------------------------------------------------------------------
iLOrest > quit
Logging session out.
Bye for now
You have new mail in /var/spool/mail/root
[root@ml150g9d39u12l ~]# mount -o bind /tmp /tmp
[root@ml150g9d39u12l ~]# mount -o remount,noexec /tmp
[root@ml150g9d39u12l ~]# ilorest
ilorest: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
[root@ml150g9d39u12l ~]# mkdir ~/mytemp
[root@ml150g9d39u12l ~]# export TMP=~/mytemp
[root@ml150g9d39u12l ~]# ilorest
iLOrest : RESTful Interface Tool version 2.1
Copyright (c) 2014, 2017 Hewlett Packard Enterprise Development Company
-------------------------------------------------------------------------------------------------------------------------------------------------
iLOrest > quit
Logging session out.
Bye for now
[root@ml150g9d39u12l ~]# unset TMP
[root@ml150g9d39u12l ~]# ilorest
ilorest: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
[root@ml150g9d39u12l ~]# export TMPDIR=~/mytemp
[root@ml150g9d39u12l ~]# ilorest
iLOrest : RESTful Interface Tool version 2.1
Copyright (c) 2014, 2017 Hewlett Packard Enterprise Development Company
-------------------------------------------------------------------------------------------------------------------------------------------------
iLOrest > quit
Logging session out.
Bye for now

strace execution with /tmp having exec privilege the child process returns a 0 status 
 
<<CUT>>
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f0653171a10) = 26413
rt_sigaction(SIGINT, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGKILL, {0x4041d0, [KILL], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {SIG_DFL, [], 0}, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTERM, {0x4041d0, [TERM], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {SIG_DFL, [], 0}, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 26413
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=26413, si_status=0, si_utime=71, si_stime=60} ---
rt_sigaction(SIGINT, {SIG_DFL, [INT], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, 8) = 0
rt_sigaction(SIGKILL, {SIG_DFL, [KILL], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTERM, {SIG_DFL, [TERM], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, {0x4041d0, [TERM], SA_RESTORER|SA_RESTART, 0x7f06531a8670}, 8) = 0
<<CUT>>
exit_group(0)                           = ?
+++ exited with 0 +++
 
And /tmp without exec privilege  it returns 127

<<CUT>>
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f1259e3ea10) = 15676
rt_sigaction(SIGINT, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGKILL, {0x4041d0, [KILL], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {SIG_DFL, [], 0}, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTERM, {0x4041d0, [TERM], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {SIG_DFL, [], 0}, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 127}], 0, NULL) = 15676
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=15676, si_status=127, si_utime=0, si_stime=0} ---
rt_sigaction(SIGINT, {SIG_DFL, [INT], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, 8) = 0
rt_sigaction(SIGKILL, {SIG_DFL, [KILL], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {0x4041d0, [INT], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTERM, {SIG_DFL, [TERM], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, {0x4041d0, [TERM], SA_RESTORER|SA_RESTART, 0x7f1259e75670}, 8) = 0
<<CUT>>
exit_group(127)                         = ?
+++ exited with 127 +++

**Comment by Yergidy** [comment]
This is an issue with the utility. Please create a new issue here:
https://github.com/HewlettPackard/python-redfish-utility
