### ISSUE TITLE
add user 

### ISSUE THREAD

**Issue by bhlzu21** [HewlettPackard/python-ilorest-library#143]
Hello,
I am currently working on an important project and I am stuck...
I have been given an iLO4 and been tasked with creating users on this interface with ansible

when using the adduser role
All I am getting after running the playbook is:

`failed: [ansible-1 -> localhost] (item={'new_username': 'admin', 'new_password': 'password', 'roleid': 'Administrator'}) => {"ansible_loop_var": "item", "changed": false, "item": {"new_password": "password", "new_username": "admin", "roleid": "Administrator"}, "msg": "HTTP Error 400 on POST request to 'https://{baseuri}/redfish/v1/AccountService/Accounts', extended message: '[{'MessageArgs': ['RoleId'], 'MessageId': 'Base.0.10.PropertyUnknown'}]'"}`

I'd be very very thankful for any help

I am aware of a previous issue with roleid not existing in iLO4 but the "fix" did not do it for me

**Comment by rajeevkallur** [comment]
Basically Roleid is not recognised by iLO4.  Please adjust the parameters in ansible playbook/role and run.

**Comment by rajeevkallur** [comment]
@bhlzu21 ,  Closing the case.  If you think it is still not working, please reopen.
