### ISSUE TITLE
Add User is not working for iLo6 firmware 1.20 (DL385Gen11)

### ISSUE THREAD

**Issue by chamingkk** [HewlettPackard/python-ilorest-library#144]
resp = _redfishobj.post(account_collection_uri, body)

An http response of '401' was returned.

/blob/master/examples/Redfish/add_user_account.py

[failed with python-ilorest-library 4.2.0.0 and 4.0.0.2]

**Comment by rajeevkallur** [comment]
@chamingkk Should be working now. Please check.
