### ISSUE TITLE
Cannot build locally

### ISSUE THREAD

**Issue by ErwanAliasr1** [HewlettPackard/python-ilorest-library#146]
I'm trying to see how I could rebuild ilorest for aarch64 users but the makefile is making a reference to github.hpe.com that is not publicly available.
Can you ensure the build procedure works for everyone ?

**Comment by rajeevkallur** [comment]
@ErwanAliasr1 , Take RHEL 8.6 ARM OS and follow the Makefile.ARM.  Use win32\rdmc-pyinstaller-spec.lin and generate ilorest binary. For rpm generation, please use rpmbuild command.
No need of github.hpe.com or blofly config.

**Comment by rajeevkallur** [comment]
Closed
