### ISSUE TITLE
unable to integrated with gevent

### ISSUE THREAD

**Issue by changsijay** [HewlettPackard/python-ilorest-library#15]
I tried to use gevent speed up scan ilo on thousands of machines.
but the library of http client seems not support gevent.

Is it possible to use gevent with python-ilorest-library?

**Comment by Yergidy** [comment]
@changsijay  We will look into this and see if it is possible.

**Comment by Yergidy** [comment]
@changsijay We will be releasing a update soon that switches the library to urllib3 which should work with gevent.  I will update this issue again once it has been released.

**Comment by Yergidy** [comment]
@changsijay version 2.4.1 of the library has now released.

**Comment by changsijay** [comment]
thank you very much, will take a try 💃
