### ISSUE TITLE
Unable to set onetime boot using ilorest 4.1.0.0

### ISSUE THREAD

**Issue by akki-9922** [HewlettPackard/python-ilorest-library#151]
Hi team, 

I am using rhel7.x machine and trying to set a onetime boot using ilorest 4.1.0.0 for HP 380 Gen 10 server but it's failing. 

My ILO version is ILO5

### **Method 1:**
/mnt/packages/x64/rest/ilorest

iLOrest : RESTful Interface Tool version 4.1.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
-------------------------------------------------------------------------------------------------------------------------------------------------------------
iLOrest > login
Discovering data...Done
iLOrest > bootorder --onetimeboot=Hdd
bootname is : Boot Order Current Settings

bootname is : Boot Order Pending Settings

bootpath is : /redfish/v1/systems/1/bios/boot/settings/
ERROR: 'str' object has no attribute 'get'

### **Method 2:**
mnt/packages/x64/rest/ilorest  bootorder --onetimeboot=Cd --commit login -u <user> -p <password>

iLOrest : RESTful Interface Tool version 4.1.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Discovering data...Done
bootname is : Boot Order Current Settings
bootname is : Boot Order Pending Settings
bootpath is : /redfish/v1/systems/1/bios/boot/settings/

After this command returns with exit code 0 but no boot device changed.

**Comment by rajeevkallur** [comment]
@akki-9922 Please check with latest 4.5.0.0.  There is no issue observed w.r.t bootorder

**Comment by rajeevkallur** [comment]
Closed
