### ISSUE TITLE
Modify User is not working for iLo6 firmware 1.20 (DL385Gen11)

### ISSUE THREAD

**Issue by chamingkk** [HewlettPackard/python-ilorest-library#153]
Modify user script failed with 401 error code. Issue cannot be seen in ilo5 (DL385Gen10).
\python-ilorest-library\examples\Redfish\modify_user_account.py

![image](https://github.com/HewlettPackard/python-ilorest-library/assets/8225377/00a8382e-d431-4765-8517-695e9a31c900)

**Comment by richotero** [comment]
This issue seems similar to mine (#154). The `ilorest` program and scripts that use the Python library work fine with iLO 5 but fail on a new server that has iLO 6.

**Comment by rajkumar14** [comment]
I have verified iLO5 and iLO6 setup. This is working as expected with latest ilorest-library. Closing the case.

**Comment by rajeevkallur** [comment]
Closed
