### ISSUE TITLE
Publish whl files to pypi

### ISSUE THREAD

**Issue by dlopes7** [HewlettPackard/python-ilorest-library#159]
Any reason why the whl files are not published to pypi? Only the source?
Having pre-built whl files would be quite handy, example the command:

```
pip download --only-binary=:all: --platform win_amd64 python-ilorest-library
```

Will fail for this library even though it is cross platform.

**Comment by rajeevkallur** [comment]
@dlopes7 , Will check this out soon

**Comment by rajeevkallur** [comment]
Wheel is also published now
