### ISSUE TITLE
_http_response.msg has no member as "header" 

### ISSUE THREAD

**Issue by husain-bhanpurawala** [HewlettPackard/python-ilorest-library#16]
https://github.com/HewlettPackard/python-ilorest-library/blob/5598096e85d4768188b87c20a06c849d0a246f65/src/redfish/rest/v1.py#L978

Actually this should have been restresp._http_response.headers so that header.rstrip() would work.
Tested this change work fine. Can you check?

**Comment by husain-bhanpurawala** [comment]
@LumbaJack

**Comment by LumbaJack** [comment]
@husain-bhanpurawala gave a look and it looks like the code is correct as it is since the headers are returned as strings. If you feel there is an issue with this approach please submit a more detailed use case so it can debugged. Please follow up with @Yergidy and @PrithviBS .

**Comment by Yergidy** [comment]
A fix for this issue has been committed.
