### ISSUE TITLE
Cannot cooenct 

### ISSUE THREAD

**Issue by Houselstein57** [HewlettPackard/python-ilorest-library#165]
Hello, 

I'm trying a redfish connection to ILO using ILO session token gotten from Oneview.
It is not working using python-ilorest-library, got an empty object:
>>> from redfish import RedfishClient
>>> REDFISHOBJ=RedfishClient(base_url=iloURL,sessionkey=iloToken)
>>> vars(REDFISHOBJ)
{'default_prefix': '/redfish/v1', 'is_redfish': True, 'root': None, 'auth_type': 'session', '_auth_key': None, '_user_pass': (None, None), '_session_location': None, '_cert_data': None, 'login_otp': None, 'connection': <redfish.rest.connections.HttpConnection object at 0x000002553C3ABD60>, '_biospassword': None}
>>>

but when using DMTF redfish it is working :
 >> import redfish
>>> REDFISHOBJ=redfish.redfish_client(base_url=iloURL,sessionkey=iloToken)
>>> vars(REDFISHOBJ)
{'_RestClientBase__base_url': 'https://XX.XX.XX.XX', '_RestClientBase__username': None, '_RestClientBase__password': None, '_RestClientBase__session_key': '6029eb116e109b5b91d94432bb28ecba',......

Thanks in advance for your help.

Yvon Housletein.

**Comment by rajeevkallur** [comment]
Will check

**Comment by rajeevkallur** [comment]
This will be fixed in upcoming ilorest version 5.3.0.0

**Comment by rajeevkallur** [comment]
Fixed in 5.3
