### ISSUE TITLE
BootOrder not showing correctly

### ISSUE THREAD

**Issue by JDParsons1** [HewlettPackard/python-ilorest-library#19]
I need to validate the bootorder is set correctly on hundreds of servers in my organization and trying to use the Restful Interface Tool to do this.    Unfortunately when I use the bootorder command or select type ComputerSystem i do not see the same boot order as when i manually login through ilo and look at current settings in BIOS.    all of my servers are set to Legacy Bootmode if that helps determine what the issue is.

**Comment by Yergidy** [comment]
@JDParsons1 Unfortunately the RESTful API can only control the boot order of UEFI. If the server is in Legacy Mode, the RESTful API changes to boot order will have no effect.
