### ISSUE TITLE
BIOS date and time

### ISSUE THREAD

**Issue by yugooo** [HewlettPackard/python-ilorest-library#20]
I would like to use the REST API to change the server BIOS date and time.
The server model is BL460c Gen 9, but is it possible to change with the REST API?

I actually try a lot, but I am not doing well.
I would be happy if anyone could help me.

**Comment by Yergidy** [comment]
We are looking into if this is possible.

**Comment by bennykusman** [comment]
Hi Yergidy,

any plan on this ?

**Comment by KeepSummerSaf3** [comment]
As an alternative, we would suggest configuring an NTP server for iLO.

**Comment by KeepSummerSaf3** [comment]
Please let us know if we can assist further, otherwise, may we close this issue?

**Comment by rajeevkallur** [comment]
Closing this issue.
