### ISSUE TITLE
Document how to pass args to get 

### ISSUE THREAD

**Issue by mlbrianr** [HewlettPackard/python-ilorest-library#22]
The iLO5 REST API Docs say that iLO5 supports the OData $expand syntax (https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#odata-expand-syntax).

Could you write an example or somehow document how to pass args to get, such as:

response = REDFISH_OBJ.get('/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/DiskDrives/', args={'$expand':'.'})

It took me a while to figure this out, and having an example might help folks.

This seems like a good idea if you're using iLO5 and have a lot of items of the same type (e.g. a DL380 populated with 24 drives) rather than having to get the Members list and then do a get on each individual one.

**Comment by Yergidy** [comment]
This is a good suggestion. We will add an example for this.
Also, just adding the expand notation to the URI should give the same results:
response = REDFISH_OBJ.get('/redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/DiskDrives/?$expand=.'

**Comment by Yergidy** [comment]
Added a new redfish example script for this:
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/ex54_expand_data.py
