### ISSUE TITLE
Support for iLO 5

### ISSUE THREAD

**Issue by herrryan** [HewlettPackard/python-ilorest-library#23]
Hi guys, does the library work for iLO 5? As an initial Test, it does not seem to work somehow. I got the following error messages:

15:22:30 Traceback (most recent call last):
15:22:30   File "create_ilo_settings_for_new_blades.py", line 194, in <module>
15:22:30     REST_OBJ = RestObject("https://" + url, iLO_account, iLO_password)
15:22:30   File "/var/lib/jenkins/workspace/tip/hpe_ilo_operation/configure_ilo_for_new_blades/hpe_ilo_operation/libs/_restobject.py", line 87, in __init__
15:22:30     default_prefix="/rest/v1")
15:22:30   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/redfish/rest/v1.py", line 1489, in rest_client
15:22:30     sessionkey=sessionkey, is_redfish=is_redfish, cache=cache)
15:22:30   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/redfish/rest/v1.py", line 1531, in get_client_instance
15:22:30     is_redfish=is_redfish, cache=cache)
15:22:30   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/redfish/rest/v1.py", line 1114, in __init__
15:22:30     self.login_url = self.root.links.Sessions.href
15:22:30 KeyError: 'links'
15:22:30 Exception AttributeError: "'RestObject' object has no attribute 'rest_client'" in <bound method RestObject.__del__ of <libs._restobject.RestObject object at 0x7f8854626190>> ignored

**Comment by Yergidy** [comment]
The object "RestObject" is for iLO 4, non-redfish servers. For iLO 5 and servers with redfish, the object "RedfishObject" is the one you should be using.

**Comment by herrryan** [comment]
Thanks a lot for the tips. It works as charm.
