### ISSUE TITLE
Remove unused old library dependency - urlparse2

### ISSUE THREAD

**Issue by trusnak** [HewlettPackard/python-ilorest-library#28]
get_cache_dirname() is never used outside of helper. Anyway, it depends on very old, unmaintained library urlparse2 - last commit is 6 years old. Library is not python3 compatible (at least it's dependecy - recordtype library).

Please, remove this dependency and change get_cache_dirname() to use built-in functions to parse URL.

What about to use this?
from urllib.parse import urlparse
 o = urlparse('http://www.cwi.nl:80/%7Eguido/Python.html')
ParseResult(scheme='http', netloc='www.cwi.nl:80', path='/%7Eguido/Python.html', params='', query='', fragment='')

**Comment by Yergidy** [comment]
Thanks. We have plans to remove urlparse2.

**Comment by Yergidy** [comment]
@trusnak We have removed urlparse2 as a dependency in version 2.4.1 of the library, which has just been released.

**Comment by trusnak** [comment]
Thank you.
