### ISSUE TITLE
pass-thro disks

### ISSUE THREAD

**Issue by eligosfx** [HewlettPackard/python-ilorest-library#30]
Hey,
How can I check how much disks and size I have with rest API if i have only pass-through disks?

**Comment by Yergidy** [comment]
@eligosfx Sorry for the slow response. Pass through disks currently aren't supported for viewing using the Rest API.

**Comment by eligosfx** [comment]
Hey,

And what about another tool like hpsassl?

**Comment by Yergidy** [comment]
@eligosfx What specifically do you mean by pass-through disks? What information are you wanting to return?

**Comment by KeepSummerSaf3** [comment]
We apologize for the extremely delayed response. By pass-through disks are you referring to virtualization/creation of logical drives and recording the parameters of those arrays within a type-1 hypervisor?

**Comment by KeepSummerSaf3** [comment]
Please advise if we can assist further; otherwise, may we close this issue?

**Comment by rajeevkallur** [comment]
Closing this issure. Please retest with latest library version and open a new case if needed
