### ISSUE TITLE
Smart Storage Config support in iLO4

### ISSUE THREAD

**Issue by nidmat** [HewlettPackard/python-ilorest-library#33]
Is smart storage configuration (Create/Delete Logical drives) supported in iLO4/Gen9 hosts?

If not, is there an alternate way to implement this?

**Comment by mgarrett33** [comment]
Hi nidmat - Smart Storage configuration is a new feature in Gen10 and iLO 5.  It is not implemented in Gen9 and iLO4.  These systems still need to use Smart Storage Administrator for configuration tasks.

**Comment by Yergidy** [comment]
If there are no other questions I will be closing this issue.

**Comment by tootTOOTBang** [comment]
It would be great to see an example of setting an array configuration for both Gen9 & 10.
