### ISSUE TITLE
Running Diagnostics without OS(remotely)?

### ISSUE THREAD

**Issue by kianrafiee** [HewlettPackard/python-ilorest-library#35]
Is there anyway to run diagnostics with ilorest? To run diagnostics(HVT) remotely on Gen9/10 servers, you have to have the server installed. I'm wondering if there is a way to do this with REST without an OS installed.

**Comment by Yergidy** [comment]
@kianrafiee Sorry for the slow response, currently there isn't a way, but it's a feature that we plan to support in the next release of HVT.

**Comment by appendages** [comment]
Hi @Yergidy Did you guys get HVT added to the REST api?

**Comment by KeepSummerSaf3** [comment]
This is coming in a future version of iLO's restful Interface in the IP Profiles (currently in the testing phases).

**Comment by rajeevkallur** [comment]
iprofiles command is available now

**Comment by hitsujihpe** [comment]
Can you share how to run HVT using ilorest?
