### ISSUE TITLE
register a server with HP Insight Remote Support

### ISSUE THREAD

**Issue by flaviotorres** [HewlettPackard/python-ilorest-library#36]
It seems this endpoint is missing on HP RedFish API. We have to add many servers into IRS (HP Insight Remote Support) Instance, does HP RedFish API provides that?

**Comment by Yergidy** [comment]
@flaviotorres Sorry for the slow response. This type may be what you're looking for: https://pages.github.hpe.com/HPE-iLO-Redfish-API/ilo5-rest-api-docs/ilo5/#hperemotesupport-v2_3_0-hperemotesupport

**Comment by Yergidy** [comment]
@flaviotorres If there are no other questions I will be closing this issue.

**Comment by flaviotorres** [comment]
Please close, that worked well! Many thanks!

**Comment by Yergidy** [comment]
Glad to have solved your issue! Closing.
