### ISSUE TITLE
installation succeed, but Python says module not found

### ISSUE THREAD

**Issue by Bareliah** [HewlettPackard/python-ilorest-library#38]
Trying to install the library in CentOS7 & python2.7.5 with no success.
Try multiple procedures:

- pip install python-ilorest-library
- git clone https://github.com/HewlettPackard/python-ilorest-library.git
  cd python-ilorest-library/
   python setup.py install
- git clone https://github.com/HewlettPackard/python-ilorest-library.git
   cd python-ilorest-library/
   python setup.py sdist --formats=zip
   cd dist
   pip install --upgrade python-ilorest-library-2.3.1.zip

Eventually, every time I'm trying to import ilorest or RedfishObject I get the error:
```
>>> import ilorest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ilorest
>>> from _redfishobject import RedfishObject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _redfishobject
```

The library looks like it installed successfully:
```
[]# pip show python-ilorest-library
---
Metadata-Version: 1.1
Name: python-ilorest-library
Version: 2.3.1
Summary: iLO Rest Python Library
Home-page: https://github.com/HewlettPackard/python-ilorest-library
Author: Hewlett Packard Enterprise
Author-email: kocurek@hpe.com
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires: jsonpatch, jsonpath-rw, jsonpointer, validictory, urlparse2, six
Classifiers:
  Development Status :: 3 - Alpha
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Topic :: Communications
```

**Comment by Yergidy** [comment]
The import name is "redfish" not ilorest. Try importing that instead and see if it works correctly.

As for _redfishobject, that object is located in our example scripts folder: https://github.com/HewlettPackard/python-ilorest-library/tree/master/examples/Redfish 

Try importing from there and see if it imports correctly.

**Comment by Bareliah** [comment]
Yes, it works like a charm! thank you!

I know it is different subject but it's related to the init process - the server is G9 so as recommended the rest object is Redfish type. 
from the web I succeed login but from the script, it throws an exception (without error message).
It failed in the init process of HttpClient:
`           super(HttpClient, self).__init__(base_url, username=username, \
                            password=password, default_prefix=default_prefix, \
                            sessionkey=sessionkey, biospassword=biospassword, \
                            cache=cache)
`
surranding it in try-except, it returns:

> 'HttpClient' object has no attribute 'root'

**Comment by Yergidy** [comment]
@Bareliah Sorry for the slow response. Depending on the iLO version redfish may not be available, which can produce this error. I'd recommend updating to the latest iLO version and retrying.

Scripting virtual media requires the iLO advanced license. See the available licenses here along with their features.
https://h20195.www2.hpe.com/v2/getpdf.aspx/4aa4-5167enw.pdf

**Comment by mhunterhpe** [comment]
I had an issue where the symlink to /usr/bin/python went to 2.x versus 3.x.

I then ran python3 quickstart.py and it ran correctly. 

Looked like the path for python2 and python3 do not share "site-package" 

my redfish/python-ilorest-library is installed to /usr/lib/python3.4/site-pagackes/redfish and the symlink or python path is pointing to the older folder.

Check permissions too!
