### ISSUE TITLE
ssl certificat verfication issue

### ISSUE THREAD

**Issue by sebastianeidner1980** [HewlettPackard/python-ilorest-library#39]
Hi, 
i got the following error:
  File "test.py", line 17, in <module>
    password=login_password)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1486, in redfish_client
    sessionkey=sessionkey, is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1556, in get_client_instance
    is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1116, in __init__
    cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 523, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 651, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError

Current System:
CentOS Linux release 7.5.1804 (Core)
Python 2.7.5 

refered to this:
https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection
if i change change it to less the version 2.7.5 if works.

537             if sys.version_info < (2, 7, 5):
538                 self._conn = http_client.HTTPSConnection(url.netloc, timeout=30)
539             else:
540                 self._conn = http_client.HTTPSConnection(url.netloc, \
541                     context=ssl._create_unverified_context(), timeout=30)
542         elif url.scheme.upper() == "HTTP":
543             self._conn = http_client.HTTPConnection(url.netloc)
544         else:
545             pass

**Comment by matthnter** [comment]
Try putting the line with password=login_password on one line.

**Comment by sebastianeidner1980** [comment]
> 
> Try putting the line with password=login_password on one line.

This was my first idea, but it doesn't work before i start troubleshooting.

Another good thing would be thats the shown error is related to the ssl problem.

**Comment by rajeevkallur** [comment]
@sebastianeidner1980, Please let us know if the issue still persists with latest versions of centOS/RHEL.

**Comment by rajeevkallur** [comment]
Please reopen if it still exists in latest versions of ilorest.
