### ISSUE TITLE
Values Missing after GET

### ISSUE THREAD

**Issue by digit82** [HewlettPackard/python-ilorest-library#4]
Here is my Python Script:

`import sys
import getopt
#import redfish
from pprint import pprint

# When running remotely connect using the iLO address, iLO account name,
# and password to send https requests
iLO_ip = ''
base= 'https://'
login_account = ''
login_password = ''
redValue = ''   #Value to serach in Redfish db
searchString = ''

from _redfishobject import RedfishObject

try:
    opts, args = getopt.getopt(sys.argv[1:], 's:u:p:r:a:h', ['iLO_ip=', 'login_account=','login_password=', 'redValue', 'searchString', 'help'])
except getopt.GetoptError as err:
    print(err)
    usage("-s ilo Host, -u iLo User, -p iLo Password")
    sys.exit(2)

for opt, arg in opts:
    if opt in ('-h', '--help'):
        usage("-s ilo Host, -u iLo User, -p iLo Password")
        sys.exit(2)
    elif opt in ('-s', '--server'):
        iLO_ip = arg
    elif opt in ('-p', '--password'):
        login_password = arg
    elif opt in ('-r', '--redValue'):
        redValue = arg
    elif opt in ('-a', '--searchString'):
        searchString = arg
    elif opt in ('-u', '--user'):
        login_account = arg
    else:
        usage("-s ilo Host, -u iLo User, -p iLo Password")
        sys.exit(2)
# dictionary with Url extensions
pathDic = {"System" : "Systems/1/", "Raid0" : "Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives/0", "Raid1" : "Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives/1", "Health" : "Chassis/1/" }

# build base https://IP
iLO_host = base + iLO_ip

# search in Array for -r Value
match = pathDic[redValue]

## Create a REDFISH object
#REDFISH_OBJ = redfish.redfish_client(base_url=iLO_host,username=login_account, \
                         # password=login_password, default_prefix='/redfish/v1')

REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)
# Login into the server and create a session
REDFISH_OBJ.login(auth="session")

# Print Search URi
Link = iLO_host + "/redfish/v1/" + match
print ( Link )

# Do a GET on a given path
response = REDFISH_OBJ.get("/redfish/v1/" +match, None)

outputList = response

outputList = str(outputList)
# Split string on "," and put in list element

outputList = outputList.split(',')

#pprint(outputList)

# search for -a string in list element
status = [s for s in outputList if searchString in s]

# Print out the response
print ( status )
#sys.stdout.write("%s\n" % response)
# Logout of the current session
REDFISH_OBJ.logout()
`

When i do a get on "/redfish/v1/Systems/1/" then e.g the Values after ""HostCorrelation" are missing.
What is wrong with my Script? I am really new to Python and i need a portable Script (pyinstaller), that i can copy to servers, to perform GET operations against remote ILO Interfaces. 

Kind Regards

**Comment by LumbaJack** [comment]
@digit82 issue under investigation will notify you when we have more information for you.

**Comment by PrithviBS** [comment]
The issue you are facing is not clear. This snippet for second part of your code has the updated functions of redfish object and works right with no issues:
"
REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)
#REDFISH_OBJ.login(auth="session")
Link = iLO_host + "/redfish/v1/" + match
print ( Link )
response = REDFISH_OBJ.redfish_get("/redfish/v1/" +match)
outputList = response
outputList = str(outputList)
outputList = outputList.split(',')
#pprint(outputList)
status = [s for s in outputList if searchString in s]
print ( status )
#sys.stdout.write("%s\n" % response)
REDFISH_OBJ.redfish_client.logout()
"
If there is data missing from the response, you will have to verify if there is an issue with the system.

**Comment by digit82** [comment]
To me it looks like, he got a Problem after "["  

"HostCorrelation": {
    "HostMACAddress": _[
      "2c:76:8a:53:XX:XX",
      "2c:76:8a:53:XX:XX",
      "2c:76:8a:53:XX:XX",
      "2c:76:8a:53:XX:XX"
    ],_
    "HostName": "srv01",
    "IPAddress": _[
      "",
      "",
      "",
      ""
    ]_
  },
I dont get IP and Mac Adresses in my response, but everthing else seems to be there.

**Comment by Yergidy** [comment]
@digit82 We aren't seeing the missing properties on our systems. To help us debug this can you provide your server model, iLO, and bios versions on the system with the issue?

**Comment by digit82** [comment]
Hi, 
i tested it with different systems.  DL380p Gen8, ILO 2.50 atm. 

When i do a get on https://ipadress/redfish/v1/Systems/1/ with a REST Client i can see all properties. 
With my Script the Block: 
"HostCorrelation":
    {
        "HostMACAddress":
        [

Is missing.

Kind Regards

**Comment by digit82** [comment]
Hey,

i think i got it resolved. I changed the line:

REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)

to:
REDFISH_OBJ = **redfish.rest_client**(iLO_host, login_account, login_password)

And now i get all the values!


Kind Regards

**Comment by PrithviBS** [comment]
Awesome.
