### ISSUE TITLE
Get the list of pending changes

### ISSUE THREAD

**Issue by mirceahusz** [HewlettPackard/python-ilorest-library#40]
Is there an api call that gives the list of pending changes? Primarily for iLO4.
Otherwise I'd have to iterate over all current vs settings and look for differences.

**Comment by PrithviBS** [comment]
Currently, we dont have this functionality readily available in the library. You can use the pending(PendingChangesCommand) command from the utility (https://github.com/HewlettPackard/python-redfish-utility) or use it as reference to write a script to do the same.

**Comment by mirceahusz** [comment]
Okay, thank you for pointing me in the right direction.

**Comment by VladoPortos** [comment]
Did you figure it out @mirceahusz  ?
