### ISSUE TITLE
_redfishobject.py library type and uri matching issue

### ISSUE THREAD

**Issue by mirceahusz** [HewlettPackard/python-ilorest-library#42]
Just an FYI, at least for iLO 5 and Gen 10 line 113 will never match 

https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/_redfishobject.py#L113

For example, searching for "Bios" resource will find:
 u'@odata.type' u'#Bios.v1_0_0.Bios'
 u'@odata.id' u'/redfish/v1/systems/1/bios/'

The left side ends up having two slashes, ie
 /redfish/v1/systems/1/bios//settings

**Comment by Yergidy** [comment]
Thanks for reporting this issue.

**Comment by Yergidy** [comment]
This file was removed in the latest release: https://github.com/HewlettPackard/python-ilorest-library/releases/latest

All of our examples now directly use the library.
