### ISSUE TITLE
SSL CA cert verification

### ISSUE THREAD

**Issue by jchia** [HewlettPackard/python-ilorest-library#43]
`redfish_client()` does not have a `cafile` argument, unlike in the latest [upstream](https://github.com/DMTF/python-redfish-library). The `RestClientBase::__init_connection()` here just uses [`_create_unverified_context()`](https://github.com/HewlettPackard/python-ilorest-library/blob/f6dae68800d20af859ed958c322108604d6a998a/src/redfish/rest/v1.py#L541), so I think it means there is no SSL certificate verification.

Are there plans to enable SSL certificate verification, e.g. by catching up to a more recent version of the upstream repo?

**Comment by Yergidy** [comment]
We are definitely interested in adding SLL certificate verification, however, in our upcoming release we have moved away from the standard `http_client` library to `urllib3`. Our implementation will need to be different than the upstream implementation which still uses `http_client`

**Comment by Yergidy** [comment]
This was added in the latest release: https://github.com/HewlettPackard/python-ilorest-library/releases/latest
