### ISSUE TITLE
"FederationConfig":    "MulticastDiscovery": "Enabled"

### ISSUE THREAD

**Issue by AnandakarPonde** [HewlettPackard/python-ilorest-library#44]
I want to set  the "MulticastDiscovery": "Enabled"  to "Disabled" . Can you please give  me the example code for that in python? 

"FederationConfig":       {
        "IPv6MulticastScope": "Site",
        "MulticastAnnouncementInterval": 600,
        "MulticastDiscovery": "Enabled"

**Comment by Yergidy** [comment]
It would be very similar to example 15: https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/ex15_set_uid_light.py

You would just need to change the search_for_type from `ComputerSystem.` to `Manager.` and update the body with your changes.

**Comment by KeepSummerSaf3** [comment]
If there are no further questions, may we consider this issue as resolved?
