### ISSUE TITLE
iLO 4 (2.42) RestObject' object has no attribute 'rest_client' (I can access the ILO interface from this host)

### ISSUE THREAD

**Issue by chilliblast** [HewlettPackard/python-ilorest-library#46]
Hi there

I am currently testing the example Python script "ex53_update_ilo_firmware.py", however I continually run into the following error:

Traceback (most recent call last):
  File "ex53_update_ilo_firmware.py", line 51, in <module>
    REST_OBJ = RestObject(iLO_https_url, iLO_account, iLO_password)
  File "/tmp/python/examples/Rest/_restobject.py", line 88, in __init__
    default_prefix="/rest/v1")
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1514, in rest_client
    sessionkey=sessionkey, is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1556, in get_client_instance
    is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1116, in __init__
    cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 523, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 651, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError
Exception AttributeError: "'RestObject' object has no attribute 'rest_client'" in <bound method RestObject.__del__ of <_restobject.RestObject object at 0x7fc7f06bad10>> ignored

This is being executed from a host on the same subnet, with full access, to the ILO interface I am testing this against (ILO 4 Gen 9 FW 2.42)

Am I doing something stupid here? 

Thanks

**Comment by Yergidy** [comment]
`redfish.rest.v1.RetriesExhaustedError` will occur if you have the wrong credentials. Other than that I'm not seeing anything that sticks out. Let me try and reproduce on my end and see if I can see what's going on.

**Comment by chilliblast** [comment]
That would be much appreciated - it is a very strange error.

I tried updating the node to:

P89 v2.64 (System ROM)
2.61 ILO FW Version

Now I get a completely different error with no change to the example code:

Traceback (most recent call last):
  File "ex53_update_ilo_firmware.py", line 51, in <module>
    REST_OBJ = RestObject(iLO_https_url, iLO_account, iLO_password)
  File "/tmp/python/examples/Rest/_restobject.py", line 88, in __init__
    default_prefix="/rest/v1")
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1514, in rest_client
    sessionkey=sessionkey, is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1556, in get_client_instance
    is_redfish=is_redfish, cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1116, in __init__
    cache=cache)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 523, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 651, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError
Exception AttributeError: "'RestObject' object has no attribute 'rest_client'" in <bound method RestObject.__del__ of <_restobject.RestObject object at 0x7f800dcc8d10>> ignored

**Comment by Yergidy** [comment]
@chilliblast I'm seeing the same traceback in both comments. Did you mean to paste something else?

**Comment by chilliblast** [comment]
Sorry @Yergidy for the confusion.

I retested this but used python-hpilo library as a comparison from the same host and against the same HP server (Gen9), I had no issues (using same creds):

>>> import sys
>>> import hpilo
>>> ilo = hpilo.Ilo(‘1.2.3.4’,’User’,’Pass’)
>>> print(ilo.get_fw_version())
{'license_type': 'iLO Advanced', 'firmware_version': '2.40', 'management_processor': 'iLO4', 'firmware_date': 'Dec 02 2015'}
>>> def print_progress(text):
...     sys.stdout.write('\r\033[K' + text)
...     sys.stdout.flush()
... 
>>> ilo.update_rib_firmware(version='latest', progress=print_progress)
Firmware flash in progress [97%].>>> 
>>> print(ilo.get_fw_version())
{'license_type': 'iLO Advanced', 'firmware_version': '2.61', 'management_processor': 'iLO4', 'firmware_date': 'Jul 27 2018'}

...so I am not sure why the original RestAPI method does not work.

Do you have any ideas?

I wasn't sure if I was doing something stupid with the example code, I have tried specifying both:

ex53_update_ilo_firmware(REST_OBJ, "file:///tmp/patch/ilo4_261.bin", False)

and also the https://downloads.hpe.com/pub/softlib2/software1/sc-linux-fw-ilo/p192122427/v154294/CP036949.scexe

and also a made up URL which does not exist

Nothing seems to make any difference to the error, wether the location exists or not, it is always that same error.

Thanks

**Comment by chilliblast** [comment]
Hi there

Were you able to reproduce this issue at all?

I also tested using "quickstart.py" (REST method) and I get exactly the same error.

We have a bunch of Gen9's here and it does not work on any of them with varying ILO FW versions (including 2.61).

Thanks

**Comment by Yergidy** [comment]
Sorry. We have not. What python version are you attempting to run these with?

**Comment by soundisloud** [comment]
I am also seeing a similar error while trying some of the examples.  I continue to raise an error on the get_root_object.

I feel like I am missing something when I read some of the documentation.  Some documentation says import ilorest, others redfish and few others variants.  Am I missing something?

**Comment by soundisloud** [comment]
> 
> 
> I am also seeing a similar error while trying some of the examples. I continue to raise an error on the get_root_object.
> 
> I feel like I am missing something when I read some of the documentation. Some documentation says import ilorest, others redfish and few others variants. Am I missing something?

So I performed a curl on the test addresses I am using.  Turns out I have to ignore the certs verification.  Could this be causing the errors here?

**Comment by soundisloud** [comment]
> 
> 
> I am also seeing a similar error while trying some of the examples. I continue to raise an error on the get_root_object.
> 
> I feel like I am missing something when I read some of the documentation. Some documentation says import ilorest, others redfish and few others variants. Am I missing something?

So I performed a curl on the test addresses I am using.  Turns out I have to ignore the certs verification.  Could this be causing the errors here?

> 
> 
> > I am also seeing a similar error while trying some of the examples. I continue to raise an error on the get_root_object.
> > I feel like I am missing something when I read some of the documentation. Some documentation says import ilorest, others redfish and few others variants. Am I missing something?
> 
> So I performed a curl on the test addresses I am using. Turns out I have to ignore the certs verification. Could this be causing the errors here?
> 
> **Update**
> 
> I was able to confirm that my issue with this error relates to having self-signed certs not recognized by my CA bundle. I put signed test certs in place and it worked as advertised.
> 
> It would be nice to disable cert verification. I am attempting to do this myself, however, I'm a noob and it will take some trial and error.

**Update2**

redfish/rest/v1  => line 469-470

I added "cert_reqs=CERT_NONE" to both ProxyManager and PoolManager.

Probably not the best solution, but it will work for lab environments.

Hope this helped.

**Comment by Yergidy** [comment]
Thanks for the information. We will re-evaluate what works best in most environments and make changes accordingly.

**Comment by Yergidy** [comment]
In urllib3 version 1.25 and greater certificates are verified by default. The urllib3 our code was built and tested on did not include this change. 

We need to update to work with the latest urllib3.

**Comment by Yergidy** [comment]
Version 2.4.2 has been released which solves this issue. It should be updated in pip shortly.

**Comment by aparnabharathan1995** [comment]
According "https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification" document i made the following change in my code :-

import sys
import certifi
import urllib3
import redfish
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs=certifi.where())

login_host = "https://##############"
login_account = "###########"
login_password = "############"
REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account,password=login_password, default_prefix='/redfish/v1')
REDFISH_OBJ.login(auth="session")
response = REDFISH_OBJ.get("/redfish/v1/systems/1", None)
sys.stdout.write("%s\n" % response)
REDFISH_OBJ.logout()


But still i am getting the same error. The error log is as attached below.

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account,password=login_password, default_prefix='/redfish/v1')
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 1027, in redfish_client
    max_retry=max_retry)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 952, in __init__
    max_retry=max_retry)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 422, in __init__
    self.get_root_object()
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 553, in get_root_object
    raise excp
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 551, in get_root_object
    resp = self.get('%s%s' % (self.__url.path, self.default_prefix))
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 585, in get
    headers=headers)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 979, in _rest_request
    args=args, body=body, headers=headers)
  File "/home/vkchlt0163/.local/lib/python3.5/site-packages/redfish/rest/v1.py", line 844, in _rest_request
    raise RetriesExhaustedError()
redfish.rest.v1.RetriesExhaustedError

**Comment by Yergidy** [comment]
@aparnabharathan1995 Can you download the latest release from pip and see if that solves your issue?

**Comment by aparnabharathan1995** [comment]
Latestversion is six-1.12.0 ryt??

**Comment by bhaskar-vasudevan** [comment]
I seem to consistently get the below with 2.4.2
Am I missing something?

C:\Users\vasudbha\Downloads\python-ilorest-library-master (1)\python-ilorest-library-master\examples>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    REST_OBJ = redfish.rest_client(base_url=iLO_host,username=login_account, password=login_password)
  File "C:\Python27\lib\site-packages\redfish\rest\v1.py", line 1231, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "C:\Python27\lib\site-packages\redfish\rest\v1.py", line 451, in __init__
    self.login_url = self.root.links.Sessions.href
KeyError: 'links'

**Comment by Yergidy** [comment]
@bhaskar-vasudevan Are you using a Gen9 or Gen10 server? The REST examples are only for the legacy REST interface from Gen9. Gen10 and on will solely use the Redfish interface. Please try again using the Redfish quickstart.

**Comment by mridulganga** [comment]
I tried the quickstart_redfish.py file against an Gen 10 iLo5. The quickstart file seems to be making use of calls which aren't present in the _redfishobject.py file. So it is causing a lot of errors since it cant find those functions. 

I have made modifications to the quickstart file which uses the functions present in the _redfishobject.py file.

```python
from _redfishobject import RedfishObject

iLO_https_url = "https://15.129.90.169"
iLO_account = "administrator"
iLO_password = "hpvse123"

REDFISH_OBJ = RedfishObject(iLO_https_url, iLO_account, iLO_password)

response = REDFISH_OBJ.redfish_get('/rest/v1/systems/1')
print(response)

REDFISH_OBJ.redfish_client.logout()
```

**Comment by Yergidy** [comment]
@mridulganga Thanks. Do you want to open a PR with your changes and we can integrate them?

**Comment by mridulganga** [comment]
> @mridulganga Thanks. Do you want to open a PR with your changes and we can integrate them?

@Yergidy I have made a pull request for the above code. Tested it on a Gen10 iLo5
Find it below:
https://github.com/HewlettPackard/python-ilorest-library/pull/56

**Comment by Yergidy** [comment]
With the 3.0 release we no longer use the `RedfishObject`.
