### ISSUE TITLE
ILO5 redfish API with Gen10  showing SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sarathchandran-vc** [HewlettPackard/python-ilorest-library#47]
while i am trying to use ex03_change_bios_setting.py getting below error. I have installed  `pip  install python-ilorest-library` and tried to execute sample script in `python-ilorest-library-master/examples/Redfish`

```
[root@AtomBuildServer Redfish]# python ex03_change_bios_setting.py
```
```
Traceback (most recent call last):
  File "ex03_change_bios_setting.py", line 16, in <module>
    from _redfishobject import RedfishObject
  File "/root/python-ilorest-library-master/examples/Redfish/_redfishobject.py", line 74, in <module>
    import redfish.ris.tpdefs
  File "/usr/lib/python2.6/site-packages/redfish/ris/__init__.py", line 36, in <module>
    from .rmc import (
  File "/usr/lib/python2.6/site-packages/redfish/ris/rmc.py", line 35, in <module>
    import redfish.ris.validation
  File "/usr/lib/python2.6/site-packages/redfish/ris/validation.py", line 313
    ttdict = {ki:val for ki, val in list(tdict.items()) if not isinstance(val, (dict, list))}
                       ^
SyntaxError: invalid syntax
```
I am doing something wrong  here ?

1) i have tried with Rest and Gen9 hardware with sane script  `change_bios_setting.py` from `/python-ilorest-library-master/examples/Rest` and its works charm .But Gen10 is not working with same script hence I tried with  Redfish but no luck ,

**Comment by Yergidy** [comment]
Python 2.7 is the minimum version supported by the library. Update to python 2.7 and see if that solves your issue.

**Comment by sarathchandran-vc** [comment]
Hi Yergidy  
Yes. once I upgraded the python to 2.7 Syntax Error is not seen now .Tried now on both Gen9 and Gne10 hardware throwing new error as below . ILO is accessible from the machine where I am running the script
```
[root@test /etc/yum.repos.d/python-ilorest-library-master/examples/Redfish]# python ex03_change_bios_setting.py
Traceback (most recent call last):
  File "ex03_change_bios_setting.py", line 61, in <module>
    raise excp
redfish.rest.v1.RetriesExhaustedError
```
