### ISSUE TITLE
SetBiosPassword

### ISSUE THREAD

**Issue by tootTOOTBang** [HewlettPackard/python-ilorest-library#49]
I have not been able to get this to work on either a G9 or G10.  Please help!!

**Comment by Yergidy** [comment]
Can I have some information on what you're doing and what error you're receiving?

**Comment by tootTOOTBang** [comment]
On the G9 I receive a message to the affect of I need to be >2.5, test machine is 2.61.  The g10 runs successfully, however, no password appears to be set.

**Comment by Yergidy** [comment]
Is this with the iLOrest tool or with the python-library? Can I have the exact message? It will help us pin-point exactly what you're running into.

If running with the iLOrest tool can I have your exact commands?

**Comment by tootTOOTBang** [comment]
I am not in my office.  That will need to wait until tomorrow, however, these errors are for both generations on the python-lib.  FYI I am following the setbiospassword example.   I can script out the changing of passwords using bash on a g10.  I have not been able to do so on a g9.  Perhaps I am stupid  <= strong possibility

**Comment by tootTOOTBang** [comment]
> I am not in my office. That will need to wait until tomorrow, however, these errors are for both generations on the python-lib. FYI I am following the setbiospassword example. I can script out the changing of passwords using bash on a g10. I have not been able to do so on a g9. Perhaps I am stupid <= strong possibility

FYI this is soundisloud.  I could not remember my password and created a new account from...not the office

**Comment by soundisloud** [comment]
Gen9, iLo version 2.61
Error:
'Bios.' resource or feature is not supported on this system
---------------------------------------------------------------
Gen10, iLo version 1.40

PATCH {'OldAdminPassword': None, 'AdminPassword': 'thingy'} to /redfish/v1/systems/1/bios/
PATCH response = 405
No entended error information returned by iLo
PATCH {'OldAdminPassword': None, 'AdminPassword': 'thingy'} to /redfish/v1/systems/1/bios/
PATCH response = 200
iLO return code iLO.2.7.SystemResetRequired: The system properties were correctly...
--------------------------------------------------------------------------------------------

I tried on two of our test machines and cannot get the BIOS password to set. 

I will keep at it, suggestions, or a pointer in a direction would be great!  Thanks!

**Comment by Yergidy** [comment]
For Gen9:
Patching must happen on the settings URI of bios: `/redfish/v1/systems/1/bios/settings/`.

For Gen10:
This has changed from a patch property to a post action. We need to update our redfish example to reflect this.

**Comment by soundisloud** [comment]
The iLO version on the G9 displays 2.61.  Is this not the version I should be concerned with?

**Comment by Yergidy** [comment]
I have updated my previous comment with more information on Gen9 Bios and the method to set the bios password or a Gen10 system if you need it before we update the example.

**Comment by tootTOOTBang** [comment]
> https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#change-bios-password

Is there, or will there be, an upgrade that will conform Gen9 to the chosen standard?

**Comment by Yergidy** [comment]
No. The Gen9 method will not change.

**Comment by Yergidy** [comment]
Version 2.4.2 has been released which solves this issue. It should be updated in pip shortly.

**Comment by KeepSummerSaf3** [comment]
If there are no further questions, may we consider this issue as resolved?
