### ISSUE TITLE
Can we set boot options for the virtualmedia?

### ISSUE THREAD

**Issue by munichman2008** [HewlettPackard/python-ilorest-library#5]
We want to set the location of the kickstart file for booting the virtualmedia, but I don't see a way to configure the iLO to boot with specific boot option?  This website describes the boot options available:

https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.install.doc/GUID-9040F0B2-31B5-406C-9000-B02E8DA785D4.html

**Comment by Yergidy** [comment]
Perhaps what you're looking for is the "UrlBootFile" or "UefiShellStartupUrl" items in the "HpBios." type?

**Comment by munichman2008** [comment]
Sorry, I asked the wrong question. Closing this issue.
