### ISSUE TITLE
v.2.4.1 - No timeout setting

### ISSUE THREAD

**Issue by danielt1984** [HewlettPackard/python-ilorest-library#50]
I have noticed that in v.2.4.1 there is no option to set the timeout, maybe I'm missing something. 
In v.2.3 there was a timeout hard coded in v1.py but in the latest version after the change to urllib3 there isn't .
I have done something that sets the timeout like this:
`REDFISH_OBJ = redfish.rest_client(base_url=iLO_https_url, username=iLO_account, \
                                          password=iLO_password, default_prefix='/redfish/v1', timeout=5 )`
I'm not a big expert and I'm sure it can be done in a more elegant way. In the attach is how I have done it.
[my_v1.py.txt](https://github.com/HewlettPackard/python-ilorest-library/files/3089509/my_v1.py.txt)

Also it would be nice to have MAX_RETRY not hard coded in v1.py and be able to set it.

**Comment by Yergidy** [comment]
Agreed. We will put this on the TODO list.

**Comment by Yergidy** [comment]
This was added in the lastest release: https://github.com/HewlettPackard/python-ilorest-library/releases/latest
