### ISSUE TITLE
[Question] Set Legacy Boot mode order on Gen 9 DL360?

### ISSUE THREAD

**Issue by rhuard** [HewlettPackard/python-ilorest-library#51]
I am trying to automate some setup we do with out servers. One step is setting the boot order, we have our servers in legacy boot mode as opposed to UEFI. We have Gen 9 ProLaint DL360 servers on firmware 2.61 Jul 27 2018.

The examples in this repo only seem to set boot mode for UEFI (based on comments and by testing it out my self - I was able to run the set boot order requests, but when I log into the ilo through the bowser the legacy mode boot order is unchanged).

I also found the python-redfish-utility, and had a similar experience, where I was able to go through the example, find the persistent boot order, change and commit it, but there was no effect on the actual legacy boot mode when I log into the ilo through browser. 

I also was able to find this post: https://community.hpe.com/t5/HPE-OneView/REST-change-boot-order/m-p/6843029#M864, however, I am unable to find the server-profiles anywhere. So I am thinking that the server-profile is deprecated at this point.

So I am just wanting to make sure I am not missing anything, if I am and it is possible to set the legacy boot mode on this server version through the REST API please point me in the right direction.

**Comment by Yergidy** [comment]
Unfortunately you cannot set Legacy Boot order with Redfish.

**Comment by rhuard** [comment]
sounds good, thank you.
