### ISSUE TITLE
[Question] configure Raid on Gen 9 DL360?

### ISSUE THREAD

**Issue by rhuard** [HewlettPackard/python-ilorest-library#52]
This is similar to my other question in issue #51, something we want to automate is setting up raid. However, the docs here I only see examples of getting the smart array configuration in the docs:
https://hewlettpackard.github.io/ilo-rest-api-docs/ilo4/?python#arraycount

things like getting number of arrays etc, nothing that seems like it would actually configure the array. I could be missing something though.

I also looked at python-redfish-utility, anytime i run any of the smartarray commands, I am getting an error saying "Unable to locate instance for smartstorageconfig".

So it seems that gen9 DL360 do not support configuring the smart array through rest is that correct or am I missing something (which I suspect I am)?

**Comment by Yergidy** [comment]
Please see issue https://github.com/HewlettPackard/python-ilorest-library/issues/33
