### ISSUE TITLE
[Question] is it possible to provide local file for firmware upgrade

### ISSUE THREAD

**Issue by rhuard** [HewlettPackard/python-ilorest-library#54]
Sorry if this is not the appropriate place to ask this question,

The firmware examples take a url argument, I am assuming that is for some file server somewhere. I was just wanting to make sure it is not possible to use a local file for that?

In other words, to upgrade the firmware from the Rest or Redfish, we will need to setup a file server that the ilos can pull the .bin file from?

**Comment by Yergidy** [comment]
Yes. The firmware examples require a file server that can communicate with iLO.

If you have a Gen10 you have the option to update the firmware through the iLO repository as well. While we currently don't have that capability in the library, it is available in the iLOrest tool with the uploadcomp command:
https://hewlettpackard.github.io/python-redfish-utility/#uploadcomp-command
Example: `ilorest --component <.bin file> --update_target --update_repository`

**Comment by rhuard** [comment]
fantastic thank you!
