### ISSUE TITLE
[Question] finding more information about firmware upgrade failures

### ISSUE THREAD

**Issue by rhuard** [HewlettPackard/python-ilorest-library#57]
I have set up a web server for the firmware *.bin file, I can wget the file so that appears to be working. However, when trying to run the example for the firmware upgrade, the HTTP post is successful, but then when I check the status I get a message saying There was an error in the previous attempt but it is ready to try again. The event log in the web application just says that there was an error upgrading firmware from the web. If I am on the web application I can upload and upgrade the firmware from that same .bin file with no issues.

I was wondering if there is any way to get more information about what might actually be going on? if there was some sort of error endpoint that would have more detailed information. This is for Gen 9 DL360's using the rest interface.

Thanks 

EDIT:
It looks like I need to be looking in message registries for more details. But I am having trouble looking up info on how to do that with the api.

**Comment by rhuard** [comment]
For what its worth, the logs on the web server are not indicating the ILO trying to get the file. So it seems to be failing before that point.

**Comment by Yergidy** [comment]
The HTTP post will be successful even if iLO cannot connect to the update server. All the success response is saying is iLO successfully received the call to attempt to grab the firmware at the location specified.

For iLO 4 you may get more information from: `/redfish/v1/Managers/1/UpdateService/`

Specifically the `Details` property. Unfortunately other than that, there isn't much extra information.

**Comment by rhuard** [comment]
Sounds good thank you. So I am pretty much stuck with "The last firmware update attempt was not successful. Ready for the next update."

Good to know. Thank you
