### ISSUE TITLE
Associate ethernet interface with its bios name

### ISSUE THREAD

**Issue by mirceahusz** [HewlettPackard/python-ilorest-library#58]
On Gen9 I want to configure which interface should PXE boot using the redfish libraries. I can do that by saying "Slot1NicBoot1", "Disabled" to /redfish/v1/systems/1/bios/settings.

Before I can target 'Slot1NicBoot1' I need to associate it with an Ethernet interface. Does anyone know how that name is associated with an interface? 

The properties listed under /redfish/v1/systems/1/EthernetInterfaces/X don't give a hint. There is an id number and UefiDevicePath, but I suspect either needs to be associated with a slot number. 

A related question as I've tried to find the association between pci slot or id number and slot number: The reference https://hewlettpackard.github.io/ilo-rest-api-docs/ilo4/#slot1nicboot1  indicates that slot1nicboot1 is under /redfish/v1/systems/1/bios, but if I search_for_type("Bios.") it comes back an empty list. This is on ilo4, firmware 2.61.

Any pointers are appreciated.

**Comment by Yergidy** [comment]
On Gen9 bios was called `HpBios.` the non-redfish standard type, so in a rest system you cannot search for the redfish name. Try creating a rest object and searching for `HpBios.`

**Comment by KeepSummerSaf3** [comment]
If there are no further issues, may we close this case?
