### ISSUE TITLE
Creating Logical drives ilo5

### ISSUE THREAD

**Issue by soundisloud** [HewlettPackard/python-ilorest-library#59]
Has anyone had any luck with this?  I am receiving back what appears to be a successful patch to /smartstorageconfig/settings but nothing ever gets created; "LogialDrives" remain empty.

Second, in ilorest help docs it states to use -1 to allocate the entirety of the disk to a LD.  Does redfish recognize this or must a whole number be used?

**Comment by Yergidy** [comment]
Redfish should take the -1 value for: `DataDriveMinimumSizeGiB` and `CapacityGiB`.

The successful patch only shows 
To gather more information on a failure you can parse the `@Redfish.Settings` message response in the non-setting URI.

**Comment by soundisloud** [comment]
I do not quite follow what you mean by the message in @Redfish.Settings.  I looked in /smartstorageconfig and did not see anything meaningful in @Redfish.Settings.  I am trying to provide something more useful on what I am seeing, but I am struggling.  The below implies to me that the PUT was successful.  In fact as you can see the response say to a restart is required.  However, no logical drive ever gets created.  Is my formatting incomplete or incorrect?

curl -X PUT -H "Content-Type: application/json" -d '{"LogicalDrives":{"CapacityGiB": -1,"Raid": "Raid1", "LogicalDriveNumber": 1, "DataDrives":["1I:3:1","2I:3:5"]} https://{server-ilo}/redfish/v1/systems/1/smartstorageconfig/settings/ -i --insecure user:pw

HTTP/1.1 200 OK
Cache-Control: no-cache
...
...

{"error":{"code":"iLO.0.10.ExtendedInfo", "message":"See @Message.ExtendedInfo for more information.","@Message.ExtendedInfo"[{"MessageId":"iLO2.$.SystemResetRequired"}]}}

**Comment by Yergidy** [comment]
Just because the PUT is successful doesn't mean there won't be an error on reboot which stops the logical drive from being added.

After a reboot, if your logical drive isn't created, an error message will be returned to `@Redfish.Settings` which you can parse for more information on what went wrong. You will need to map the error response from `@Redfish.Settings` to a smartstorageconfig error registry to get more information on the issue.

**Comment by soundisloud** [comment]
Do you happen to have a link to a smartstorageconfig error registry.  I believe the error I am getting is ".../CanAddEditableDataDariveNotAllowed", however, I am not too sure on how to respond to that because ilorest creates the LD with the same user.

**Comment by Yergidy** [comment]
I do not, but it should be available in `/redfish/v1/registries/`. The URI you are looking for should mention `SmartStorageMessages`

**Comment by soundisloud** [comment]
Do you happen to have a link to a smartstorageconfig error registry.  I believe the error I am getting is ".../CanAddEditableDataDariveNotAllowed", however, I am not too sure on how to respond to that because ilorest creates the LD with the same user.

**Comment by soundisloud** [comment]
What a trip this was!  I finally figured out the issue which I will summarize below.  This excise did provide me with a deeper understanding of all the components involved, so I am grateful for that.  Thank you!

DataGuard: Disable
I overlooked this critical step when forming the body to the PUT.
