### ISSUE TITLE
Number of OS bootable drives

### ISSUE THREAD

**Issue by shunq** [HewlettPackard/python-ilorest-library#60]
I know this is regarding Legacy Boot, but still, we need this badly :( : 
We have to change manually on all G10s coming our way, the following settings:

F9 for system utilities
System configuration
RAID Card ( HPE Smart Array P408i-p SR Gen10 )
Set Bootable Devices(s) for Legacy Boot Mode
Number of OS bootable drives -- Change from 2 to 4 -- Submit changes

Could we get them changed in a easier way? Can't find anything about it while browsing though the API. If not, could I create a ticket somewhere to have it set to 4 as default since we have a bootable logical drive on position 3?

**Comment by KeepSummerSaf3** [comment]
Legacy boot order changes are unfortunately not available in Redfish. [CONREP](https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-a00007607en_us) may be a viable alternative.

**Comment by KeepSummerSaf3** [comment]
Please advise if we can assist further; otherwise, may we close this issue?

**Comment by rajeevkallur** [comment]
Closing this.
