### ISSUE TITLE
ImportError: cannot import name rest_client

### ISSUE THREAD

**Issue by saturnsbelt703** [HewlettPackard/python-ilorest-library#61]
Like what other users have posted here, I'm having issue with a file called tpdefs.py . The traceback is:

```
Traceback (most recent call last):
  File "C:/TestAutomation/src/reboot_server_iLo.py", line 5, in <module>
    from _redfishobject import RedfishObject
  File "C:\TestAutomation\src\_redfishobject.py", line 74, in <module>
    import redfish.ris.tpdefs
  File "C:\Python27\lib\site-packages\redfish\ris\tpdefs.py", line 22, in <module>
    from redfish import redfish_client, rest_client
ImportError: cannot import name rest_client
```

I installed the python-ilorest-library successfully and I am using the "reboot server" example from the gitHub page to test if the API works but it seems like there is a circular dependency or something. I'm using python version 2.7.16 and pip has been updated to the latest version. How can I solve this issue ? I am using pyCharm and when I click on rest_client from

`from redfish import redfish_client, rest_client`

it doesn't show where rest_client is used else in the file but I did find that it is used one time around line 70:

              ```
              try:
                    restclient = getclient(rest_client)
                    self.is_redfish = False
                    client = restclient 
```

How can I solve this issue ? Thanks for the help!

**Comment by jimmylin212** [comment]
Not sure if you solve this problem yet. Do you follow the guide [here](https://github.com/HewlettPackard/python-ilorest-library#id2) to install or install redfish directly from pip. if you install from pip, then it might goes failed because the code are different. I am using python 27 and there is no problem to run example `04_reset_server.py`.

**Comment by jimmylin212** [comment]
We are not able to reproduce your issue. Please make sure your python-ilorest-library's version is 2.4.2 or try to build from the source and try again. 

Thank you.

**Comment by adityakumarpinjala** [comment]
when trying to run the below,i am getting the error mentioned,can someone please help me.

import redfish.ris.tpdefs
getting the below error like this

ImportError: cannot import name 'rest_client' from 'redfish'
ImportError                               Traceback (most recent call 
last)
<ipython-input-38-a77772d388a6> in <module>
----> 1 import redfish.ris.tpdefs
~\AppData\Local\Continuum\anaconda3\lib\site- 
packages\redfish\ris\tpdefs.py in <module>
 20 import logging
 21 
---> 22 from redfish import redfish_client, rest_client
 23 from redfish.rest.v1 import ServerDownOrUnreachableError
 24 from redfish.ris.rmc_helper import UnableToObtainIloVersionError
ImportError: cannot import name 'rest_client' from 'redfish' 
(C:\Users\pinjala\AppData\Local\Continuum\anaconda3\lib\site- 
packages\redfish\__init__.py)

**Comment by KeepSummerSaf3** [comment]
We are unable to replicate this issue.

To verify versions available through pip please try: 
`pip install python-ilorest-library==` 
To verify versions installed on system:
`pip freeze`

Suggestions:
1. Try uninstalling the previous version before upgrading?
2. Have you tried installing from source as an alternative?

**Comment by rajeevkallur** [comment]
Please use latest python-ilorest-library (currently 3.0)
Documentation is at https://hewlettpackard.github.io/python-ilorest-library/
