### ISSUE TITLE
ModuleNotFoundError: No module named 'redfish'

### ISSUE THREAD

**Issue by zz823830** [HewlettPackard/python-ilorest-library#62]
I installed the ilorest module. When I tried to run it errors out

Traceback (most recent call last):
  File "C:/python/python-ilorest-library-master/examples/Redfish/ex16_computer_details.py", line 16, in <module>
    from _redfishobject import RedfishObject
  File "C:\python\python-ilorest-library-master\examples\Redfish\_redfishobject.py", line 74, in <module>
    import redfish.ris.tpdefs
ModuleNotFoundError: No module named 'redfish'

Process finished with exit code 1

I am running python 3.7

**Comment by topritchett** [comment]
Looks like the python-ilorest-library is not properly installed.
Try following the steps to install the latest version of the library.
https://github.com/HewlettPackard/python-ilorest-library#Installing

Hope that helps.

**Comment by KeepSummerSaf3** [comment]
If there are no further issues, may we close this case?

**Comment by zz823830** [comment]
Yes thanks
