### ISSUE TITLE
ModuleNotFoundError: No module named 'camelcase'

### ISSUE THREAD

**Issue by ElectroP** [HewlettPackard/python-ilorest-library#63]
I have installed camelcase module using "pip install --proxy=https://hostname:password@IP:port camelcase" this command but when i am trying to import this module it is showing ModuleNotFoundError: No module named 'camelcase' error. Can someone plz help?

**Comment by airsoftsoldrecn9** [comment]
Could you please provide the error you are experiencing when creating a Rest or Redfish object instance or running through the examples?

**Comment by KeepSummerSaf3** [comment]
If there are no further issues, may we close this case?

**Comment by DinosaurKing10** [comment]
Hello, i've been installing camelcase with 'pip install camelcase' in the terminal, every time I run the code, the error keeps appearing: ModuleNotFoundError: No module named 'camelcase'. I need help, please :c
