### ISSUE TITLE
Examples not working for rest or redfish 

### ISSUE THREAD

**Issue by rbeldin** [HewlettPackard/python-ilorest-library#66]
I am trying to use the examples quickstart.py and quickstart_redfish.py as the basis for resolving a claim a customer has and I can't get either to work to either a gen10 (ilo5) or gen9 (ilo4) server.  My base OS is RHEL 7.4 and I cloned the library earlier today.  

For ILO5 I get these errors, after changing the ip address, login, and password to match the ilo: 

'[root@b460100447 examples]# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 17, in <module>
    password=login_password)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1247, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 453, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 602, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError
[root@b460100447 examples]# python quickstart_redfish.py
Traceback (most recent call last):
  File "quickstart_redfish.py", line 17, in <module>
    password=login_password)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1247, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 453, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 602, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError'

I get the same results for both and I don't think I am ever making the connection.  

DEspite that, I can use curl or the ilorest utility to login to these ilos just fine.  

Is there a python versioning problem?   RHEL 7 uses python 2.7: 

 rpm -q python
python-2.7.5-80.el7_6.x86_64

I built the library today:  

python-ilorest-library           2.5.1

I thought perhaps it was a certificate issue but now it seems more like some problem inside the library or something it is getting during setup. 

I'm not sure what I am doing wrong here.  Any thoughts?

**Comment by topritchett** [comment]
Hello @rbeldin 
The "quickstart.py" example is meant to work on systems with the legacy REST application. (gen9 systems with an older version of iLO4).
The "quickstart_redfish.py" example is for systems with a newer version of iLO4 and all iLO5 systems.

I just tested across my servers using Centos 7 with python-2.7.5-80.el7_6.x86_64 and it is working with python-ilorest-library 2.5.1.

Could you provide the output of "quickstart_redfish.py" as well as the versions of iLO you are using?

**Comment by rbeldin** [comment]
Hi @topritchett ...

Thanks for the response.  A few questions: 

- What do you mean about 'older'?  The gen9  I was testing had ilo 2.62

- I guess I am not sure about compatibility here.   Is it expected that you would use different interfaces depending on the ilo?   Or does redfish supercede the REST interface?

I'll re-test and carefully document what I am attempting to interact with. 

By the way, this is just a side issue to the real problem. :)  The end customer claims that they can't BaseNetworkAdapters info with curl or python unless they are logged into the web gui at the same time.  This doesn't seem to make a lot sense, given that I would expect each instance to have their own session. 

Rick

**Comment by rbeldin** [comment]
Ok, here is a gen10 note working with the quickstart_redfish.py.

iLO Advanced 1.43 at  May 23 2019

[root@b460100447 examples]# python quickstart_redfish.py
Traceback (most recent call last):
  File "quickstart_redfish.py", line 17, in <module>
    password=login_password)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 1247, in get_client_instance
    is_redfish=is_redfish, cache=cache, proxy=proxy)
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 453, in __init__
    self.get_root_object()
  File "/usr/lib/python2.7/site-packages/redfish/rest/v1.py", line 602, in get_root_object
    raise excp
redfish.rest.v1.RetriesExhaustedError

**Comment by topritchett** [comment]
It could be a issue with the iLO url. Are you using the iLO IP address, or the iLO Hostname?
e.g. 
iLO_host = "https://192.168.5.102"
 or 
iLO_host = "https://ilo.int.example.com"

**Comment by rbeldin** [comment]
Both: 

iLO_host = "https://10.226.233.117"
iLO_host = "https://ilo-b460100447.alf1.global.tslabs.hpecorp.net"

Curl to the same address works.  I thought a trailing / was needed but that doesn't make a difference. 

I also thought perhaps an https_proxy environment variable in the environment, but that isn't it either. 

Can you use the library as a non-Administrator user?   The lab gave me an ilo account that lacks some privileges.  For example, I can't terminate sessions or create users, but I can reset the ilo. 

I get these same examples working to a system where I have full administrator access.

**Comment by jimmylin212** [comment]
Hi @rbeldin 

It's able to turn on the log and this might provide some useful information. Please enable the log by add the following code right before `redfish.redfish_client()` in `quickstart_redfish.py` and provide the log to us. The log will be wrote in `quickstart_failed.log` 

```python
LOGGERFILE = "quickstart_failed.log"
LOGGERFORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOGGER = redfish.redfish_logger(LOGGERFILE, LOGGERFORMAT, logging.DEBUG)
LOGGER.info("HPE Redfish API examples")
```

Thank you.

**Comment by matthnter** [comment]
Try just the IP address or hostname, no HTTPS

**Comment by rbeldin** [comment]
Well,  I don't know what was going on with my testing, but they started working. 

The customer who started all of this reported "they found that iLO4 FW 2.70 is able to populate all the details. They just need to wait for some time (2 minutes and 10 seconds) after updating iLo FW."  That was the first I had heard that they were trying to talk to the ILO right after a fw upgrade... 

Thanks for your guidance.
