### ISSUE TITLE
redfish.__version__ still refrences version 2.4.2

### ISSUE THREAD

**Issue by tijuca** [HewlettPackard/python-ilorest-library#69]
https://github.com/HewlettPackard/python-ilorest-library/blob/master/src/redfish/__init__.py#L4 still has a hardcode version string 2.4.2 which isn't reflecting the recent version 2.5.2.

**Comment by KeepSummerSaf3** [comment]
Noted. The change will be appropriately updated in 3.0.0 and subsequent versions going forward.

**Comment by tijuca** [comment]
I've tried get the version in setup.py included from the __init__.py so the library version is only written and maintained in one place. But I'm unable to bring up a good enough patch for this.

**Comment by Yergidy** [comment]
This is fixed in the latest release: https://github.com/HewlettPackard/python-ilorest-library/releases/latest
