### ISSUE TITLE
get license Key iLO4

### ISSUE THREAD

**Issue by hassan-ayo** [HewlettPackard/python-ilorest-library#70]
When running the get license Key script ( Redfish Librairy) on iLO 5 everything is working fine but the same script on iLO4 gives me 

        License: iLO Advanced
	LicenseType: Perpetual
	LicenseKey: xxxxx-xxxxx-xxxxx-xxxxx-ABCD
	No extended error information returned by iLO.

I tried also with Rest script but the same issue
Help plz

**Comment by KeepSummerSaf3** [comment]
Couple of issues seem to be present, sorry about that.

It appears the expected Hpe key on iLO4 systems may not be entirely accurate based on the iLO Firmware Version. You may try next(iter(<dict>)) as a method to quickly obtain the next available nested key and subsequent dictionary without specifying the identifier for it. This trick is only useful if one nested key, value pair is present.

For example in lines 38-40 of the get_license_key_example, you may try:
```
managers_members_response = _redfishobj.get(managers_members_uri)
hp_hpe = next(iter(managers_members_response.obj.Oem))
license_collection_uri = managers_members_response.obj.Oem[hp_hpe].Links['LicenseService']\
                                                                                    ['@odata.id']
```

We also made a mistake around line 44-45.
`license_data = _redfishobj.get(license_collection_members_uri).dict`
which should be:
`license_data = _redfishobj.get(license_collection_members_uri)`

(or you can remove the attribute '.obj' on the lines 57-58 and 60-61.

**FYI:  iLO4 does not reveal the full key, only the last 5 character group**

**Comment by hassan-ayo** [comment]
First thank you for your time and feed back ,
I cannot find the lines mentioned , my get script is bellow 

def get_license_key(redfishobj):
    if redfishobj.typepath.defs.isgen9:
        instances = redfishobj.search_for_type("HpiLOLicense.")
    else:
        instances = redfishobj.search_for_type("HpeiLOLicense.")
    license_result = dict()
    licenseproperties = ["License", "LicenseType"]
    for instance in instances:
        response = redfishobj.redfish_get(instance["@odata.id"])
        license_result["License"] = response.dict["License"]
        for licenseproperty in licenseproperties:
             sys.stdout.write("\t" + licenseproperty + ": " + \
                             str(response.dict[licenseproperty]) + "\n")
             licenseproperty = str(response.dict[licenseproperty])
        try:
            lickey = response.dict["ConfirmationRequest"]["EON"]["LicenseKey"]

        except KeyError:
            lickey = response.dict["LicenseKey"]
            sys.stdout.write("\t" + "LicenseKey" + ": " + lickey + "\n")

        redfishobj.error_handler(response)
    return (license_result)

if __name__ == "__main__":
      
                iLO_https_url = "https:// x.x.x.x"
                iLO_account = "xxxxxxx"
                iLO_password = "xxxxxxxxxx"

    # Create a REDFISH object
                try:
                        REDFISH_OBJ = RedfishObject(iLO_https_url, iLO_account, iLO_password)
                except ServerDownOrUnreachableError as excp:
                        sys.stderr.write("ERROR: server not reachable or doesn't support " \
                                                                "RedFish.\n")
                        sys.exit()
                except Exception as excp:
                        raise excp
                get_license_key(REDFISH_OBJ)

Regards

**Comment by KeepSummerSaf3** [comment]
Without formatting I am unable to tell where your for loop ends, but it appears fine. Not sure what is going on with:
`licenseproperty = str(response.dict[licenseproperty])`

If your question is why are you receiving this?
> License: iLO Advanced
> LicenseType: Perpetual
> LicenseKey: xxxxx-xxxxx-xxxxx-xxxxx-ABCD
> No extended error information returned by iLO.

Then please review the following full iLO 4 payload and note your concerns:

'@odata.type': '#HpiLOLicense.1.0.0.HpiLOLicense'
'@odata.id': '/redfish/v1/Managers/1/LicenseService/1/'
'@odata.context': '/redfish/v1/$metadata#Managers/Members/1/LicenseService/Members/$entity' 
'LicenseType': 'Internal'
'LicenseKey': 'xxxxx-xxxxx-xxxxx-xxxxx-XXXXX'
'Description': 'iLO License View'
'License': 'iLO Advanced Limited NFR'
'links': {'self': {u'href': '/rest/v1/Managers/1/LicenseService/1'}}
'LicenseExpire': 'Date-restricted license expires on Wed Jan 01 2020.'
'Type': 'HpiLOLicense.1.0.0'
'Id': '1'
'Name': 'iLO License'

**Comment by hassan-ayo** [comment]
Thank you for the help

**Comment by KeepSummerSaf3** [comment]
You are welcome. If you have no further questions, may we consider this issue as resolved and close this case?

**Comment by hassan-ayo** [comment]
Yes sure , close it please

**Comment by hassan-ayo** [comment]
Can you please keep it opened . I used a perl + xml script for that but it's not a good idea ...

My question was why the license key retrieved from iLO4 has on the 4 first fields only x , on the last field I can see the 4 digits ::

LicenseKey: xxxxx-xxxxx-xxxxx-xxxxx-ABCD

On iLO5 it works fine .

I used the ex45_get_license_key.py script .

Any idea please .

**Comment by Yergidy** [comment]
This is due to a difference in the API of iLO 4 and iLO 5. Unfortunately we cannot get the full license key on an iLO 4 system.

**Comment by hassan-ayo** [comment]
Roger That , thank you for the feed back

**Comment by Yergidy** [comment]
Closing.
