### ISSUE TITLE
Odd results when fetching /redfish/v1/ on Gen8 and Gen9 servers. Also lack of a timeout function.

### ISSUE THREAD

**Issue by thunderzzu** [HewlettPackard/python-ilorest-library#80]
Hey,

I'm experiencing an odd issue. When GET-ting /redfish/v1/ endpoint on a Gen8 (iLO v2.70), Gen9 (iLO v2.70) and Gen10 (iLO 1.44), I'm getting different results when using python-ilorest-library==3.0.0 and Python 3.6.8, than I am getting by using SoapUI.

Example: GET /redfish/v1/ with python-ilorest-library on a Gen9 server

```
#!/usr/bin/python3

import redfish
import json
from redfish.rest.v1 import ServerDownOrUnreachableError

iLO_host="https://x.x.x.x"
login_account="user"
login_password="pass"

REDFISHOBJ = redfish.RedfishClient(base_url=iLO_host, username=login_account, password=login_password)
REDFISHOBJ.login()
timedata = json.loads(REDFISHOBJ.get("/redfish/v1/").read)
print(timedata)
REDFISHOBJ.logout()
```

Result:
`
{'@odata.context': '/redfish/v1/$metadata#ServiceRoot.ServiceRoot', '@odata.id': '/redfish/v1/', '@odata.type': '#ServiceRoot.1.0.0.ServiceRoot', 'AccountService': {'@odata.id': '/redfish/v1/AccountService/'}, 'Chassis': {'@odata.id': '/redfish/v1/Chassis/'}, 'EventService': {'@odata.id': '/redfish/v1/EventService/'}, 'Id': 'v1', 'JsonSchemas': {'@odata.id': '/redfish/v1/Schemas/'}, 'Links': {'Sessions': {'@odata.id': '/redfish/v1/SessionService/Sessions/'}}, 'Managers': {'@odata.id': '/redfish/v1/Managers/'}, 'Name': 'HP RESTful Root Service', 'Oem': {'Hp': {'@odata.type': '#HpiLOServiceExt.1.0.0.HpiLOServiceExt', 'Links': {'ResourceDirectory': {'@odata.id': '/redfish/v1/ResourceDirectory/'}}, 'Manager': [{'DefaultLanguage': 'en', 'FQDN': '', 'HostName': '', 'Languages': [{'Language': 'en', 'TranslationName': 'English', 'Version': '2.70'}], 'ManagerFirmwareVersion': '2.70', 'ManagerType': 'iLO 4'}], 'Sessions': {'CertCommonName': '', 'KerberosEnabled': False, 'LDAPAuthLicenced': True, 'LDAPEnabled': False, 'LocalLoginEnabled': True, 'LoginFailureDelay': 0, 'LoginHint': {'Hint': 'POST to /Sessions to login using the following JSON object:', 'HintPOSTData': {'Password': 'password', 'UserName': 'username'}}, 'SecurityOverride': False, 'ServerName': ''}}}, 'RedfishVersion': '1.0.0', 'Registries': {'@odata.id': '/redfish/v1/Registries/'}, 'SessionService': {'@odata.id': '/redfish/v1/SessionService/'}, 'Systems': {'@odata.id': '/redfish/v1/Systems/'}, 'UUID': ''}
`

vs. what SoapUI provides

![image](https://user-images.githubusercontent.com/15312863/72615958-2598a780-3936-11ea-8a8f-fbbfa737d41e.png)

You can see that the Time, Type and Links indexes are missing in the response via Python.
When doing the same exact thing with a Gen10 server, I'm getting identical results with the Python scripts as I am with SoapUI

While we're at it, I'd like to ask on how to set timeouts when connecting to servers. I can see there's a ServerDownOrUnreachable exception mentioned in the source code, but I haven't been able to trigger it yet - when parsing a server, that's unreachable, the code never exists or throws and exception - on version 2.5.2 I had a function to catch the Exception message (It's a dirty fix, but it works) and parse the error (invalid credentials, timeout or unknown error) however now, I'm unable to do so. 
It would be great if we could define how long REDFISHOBJ.login() keeps trying to connect before throwing a timeout exception.

**Comment by Yergidy** [comment]
@thunderzzu Sorry for the slow response. On iLO 4 systems with Redfish and LegacyRest backwards compatibility both are returned. Part of creating the RedfishClient is us added the header `OData-Version: 4.0` which will remove the old LegacyRest properties `Type`, `Links`, etc. If you pass the extra header via SoapUI you should get the same results.

As for adding a timeout: See the following documentation on passing extra args down to urllib3: 
https://hewlettpackard.github.io/python-ilorest-library/Advanced-Usage.html#modifying-remote-connection-settings
