### ISSUE TITLE
Power meter Redfish call is not providing correct CPU Utilization

### ISSUE THREAD

**Issue by ankur1608** [HewlettPackard/python-ilorest-library#81]
Hi,
I am using Redfish call "/redfish/v1/chassis/1/Power/PowerMeter/" which shows below output-

{
    "@odata.context": "/redfish/v1/$metadata#HpePowerMeter.HpePowerMeter",
    "@odata.etag": "W/\"02EBA479\"",
    "@odata.id": "/redfish/v1/Chassis/1/Power/PowerMeter/",
    "@odata.type": "#HpePowerMeter.v2_0_1.HpePowerMeter",
    "Id": "PowerMeter",
    "Average": 130,
    "Maximum": 338,
    "Minimum": 109,
    "Name": "PowerMeter",

    "PowerDetail": [
        {
            "AmbTemp": 18,
            "Average": 135,
            "Cap": 0,
            "CpuAvgFreq": 0,
            "CpuCapLim": 100,
            "CpuMax": 0,
            "CpuPwrSavLim": 100,
            "CpuUtil": 0,

Here CPU utils for few servers always coming "0" while I am running stress on these servers and using "top" command inside server, I can see cpu utilization is "25%".

Let me know if there is any pre-requisite which I an missing, So, it is not able to fetch correct cpu utilization.

JFYI, I am using it for ILO5 (1.45 Jun 27 2019). Gen10 DL server having Centos OS.

**Comment by mgarrett33** [comment]
Thank you - we'll take a look at it.

**Comment by kaviyajm** [comment]
Hi,

can you please raise a quix or bring it to the iLO team, regarding the issue.

**Comment by rajeevkallur** [comment]
Please put enough or considerable load the server before running the GET redfish call.
