### ISSUE TITLE
redfish.rest.connections.RetriesExhaustedError

### ISSUE THREAD

**Issue by hassan-ayo** [HewlettPackard/python-ilorest-library#82]
add_ilo_user_account.py works fine with one iLO ip address 
But when I tried to read many iP from a file , it gives the error : redfish.rest.connections.RetriesExhaustedError .

    f = open('ilo_ip.txt', 'r')
    ip_add = f.readline()
    for x in ip_add:
        SYSTEM_URL = "https://" + str(x)
        LOGIN_ACCOUNT = "admin"
        LOGIN_PASSWORD = "password"

        REST_OBJ = LegacyRestClient(base_url=SYSTEM_URL, username=LOGIN_ACCOUNT, 
                                                            password=LOGIN_PASSWORD)
        REST_OBJ.login()
        sys.stdout.write("\nCreate an iLO User Account\n")
        add_ilo_user_account(REST_OBJ, str(name), str(username), str(password))
        REST_OBJ.logout()

Any idea ?

**Comment by Yergidy** [comment]
What iLO version are the systems running?

**Comment by hassan-ayo** [comment]
iLO4

**Comment by Yergidy** [comment]
Looks like you are iterating over the line instead of the IPs in the file. You need to change how your for loop works. In addition make sure you strip off the trailing '\n' or you will get errors.

**Comment by hassan-ayo** [comment]
I changed the loop to   with open (...) as f: 
It works fine 
Thank you for the help
