### ISSUE TITLE
iLO.2.4.PropertyNotWritableOrUnknown

### ISSUE THREAD

**Issue by hassan-ayo** [HewlettPackard/python-ilorest-library#84]
Hi All ,

the add_user_account.py from redfish folder works fine on the most iLO5 , but some of them return the message bellow without creating the account : 
[
    {
        "MessageArgs": [
            "RoleId"
        ], 
        "MessageId": "iLO.2.4.PropertyNotWritableOrUnknown"
    }
]

Process finished with exit code 0

**Comment by Yergidy** [comment]
This is due to the same issue with running the redfish example on iLO 4, the RoleId wasn't available in earlier iLO versions. We are fixing the example so it works across all versions, but in the meantime the same fix can be found in issue #76

**Comment by hassan-ayo** [comment]
Roger that 
Thank you for your feed back

**Comment by rajeevkallur** [comment]
Fixed
