### ISSUE TITLE
Python links on documentation site are all dead

### ISSUE THREAD

**Issue by evan-chaney** [HewlettPackard/python-ilorest-library#88]
All the python links on the [documentation website](https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/?python) that link to this repo are dead links. I know there is a separate repo for those docs [here](https://github.com/HewlettPackard/ilo-rest-api-docs) however they are not accepting issues and there is no contact information so there is no other way to request that be updated.

**Comment by rajeevkallur** [comment]
Hi, I am not able to verify this. Can you please provide the screenshot of one of the the link which is dead?

**Comment by TimRots** [comment]
Noticed the same issue while trying to find some info via https://hewlettpackard.github.io/ilo-rest-api-docs/ilo4/#example-reset-all-bios-and-boot-order-settings-to-factory-defaults

Example 404's:
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/ex06_bios_revert_default.py
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Rest/ex06_bios_revert_default.py

**Comment by evan-chaney** [comment]
There is this screenshot from the Example Use Cases section which links to https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/_redfishobject.py (the link is the text "RedfishObject source code") which is a 404.
![Screenshot from 2020-08-12 09-59-27](https://user-images.githubusercontent.com/5429128/90031196-91e84900-dc82-11ea-8a06-df3f0342174e.png)

**Comment by KeepSummerSaf3** [comment]
Please reference the following URL instead: https://hewlettpackard.github.io/python-ilorest-library/Examples.html
The links noted above (within the Redfish API documentation), separate from the library will be noted and addressed.

**Comment by Tamerz** [comment]
> Please reference the following URL instead: https://hewlettpackard.github.io/python-ilorest-library/Examples.html
> The links noted above (within the Redfish API documentation), separate from the library will be noted and addressed.

That link doesn't seem to work either. I get a 404 error.

**Comment by sagar-annigeri** [comment]
Can yo, please check once again the below links:
https://hewlettpackard.github.io/python-ilorest-library/Examples.html
https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/bios_revert_default.py

**Comment by evan-chaney** [comment]
Those links work but there are plenty of broken ones on the page still.
The one under the heading Reading BIOS Current Settings with text "RedfishObject source code" links to https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/_redfishobject.py which 404s.
Same with the following 
"For a full Redfish example click here: ex03_change_bios_setting.py" : https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/ex03_change_bios_setting.py
"For a full Redfish example click here: ex06_bios_revert_default.py" : https://github.com/HewlettPackard/python-ilorest-library/blob/master/examples/Redfish/ex06_bios_revert_default.py
"Redfish DMTF standard at http://www.dmtf.org/standards/redfish" : http://%20www.dmtf.org/standards/redfish

**Comment by rajeevkallur** [comment]
HPE iLO Team is working on updating the documentation and links
