### ISSUE TITLE
How to perform secure erase using REST API ?

### ISSUE THREAD

**Issue by munichman2008** [HewlettPackard/python-ilorest-library#9]
I would like to perform the HP iLO Secure Erase using automation, instead of having to manually go into the Intelligent Provisioning area and selecting "Erase Utility".  Can you provide an example to perform this task? Or is this a question for the python-redfish-utility (https://github.com/HewlettPackard/python-redfish-utility) ? 

Thanks!

**Comment by Yergidy** [comment]
Here is the documentation for the iLO REST API. You should be able to find what you're looking for here:
https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/

**Comment by Yergidy** [comment]
If there are no other questions I will be closing this issue.
