### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by mbethke** [HewlettPackard/python-ilorest-library#94]
I'm searching for a CSDL or JSON definition of HPE's OEM extensions to Redfish. {{docs/iLO_4_REST_API_Data_Model.md}} looks promising, but the contained link to h22208.www2.hp.com is (unsurprisingly - it's 2020, can someone please introduce the concept of hiding your internal servers behind a load balancer at HPE?) broken.
Any ideas where to find it?

**Comment by rajeevkallur** [comment]
Fixed
It is at https://techhub.hpe.com/eginfolib/servers/docs/HPRestfultool/iLo4/data_model_reference.html

**Comment by mbethke** [comment]
BTW, isn't there a machine readable version available? As Redfish interfaces are usually defined in CSDL or JSON, it would be vastly less work to generate the interface code from that.
