### ISSUE TITLE
Memory Status Field 

### ISSUE THREAD

**Issue by md-thomas** [HewlettPackard/python-ilorest-library#97]
The status field for memory is not present when a dimm is reporting bad, and has been removed by the chassis.
I thought the status field would be preset, but health and state, would indicate the error.

**Comment by KeepSummerSaf3** [comment]
Could you provide the data for the failing memory module within @odata.type "Memory"? Filter by Id
(Alternatively, use the URI for the procXdimmX, where X is the processor socket and dimm is the slot tied to that CPU). Depending on the level of failure, the module may not even be recognized by the motherboard, which could be one explanation.

**Comment by md-thomas** [comment]
I do have an update.
When a memory module is mapped out, i.e. the dimmstatus reports MapOutConfiguration, there is no status/health field.
It seems weird that there is no status/health fields in this case.  When a module isn't installed there is a status/health field, 
it is just set to absent.  Which is fine.

Also, when this error occurs, the Hardware status/health fields still reports OK, vs BAD or WARN.

**Comment by rajeevkallur** [comment]
Closing this case.  Please test with latest ilorest library and open a new issue if needed.
