### ISSUE TITLE
Slot1NicBoot1=NetworkBoot not working in Legacy Bios

### ISSUE THREAD

**Issue by sarathchandran-vc** [HewlettPackard/python-ilorest-library#98]
•	What is the generation and model of the server you are trying to execute the command : DL360Gen10. in Legacy Bios
•	Are you facing issue with one server or all of the servers in same generation : All the servers
•	What is the NIC card : Ethernet 10Gb 2-port 562SFP+ Adapter
•	iLO version : 2.36

```
usr/sbin/ilorest --nologo login https:// -u -p
/usr/sbin/ilorest select Bios.v1_0_0
/usr/sbin/ilorest set Slot1NicBoot1=NetworkBoot
```

I am using the above command to enable the NetworkBoot

**Comment by KeepSummerSaf3** [comment]
Legacy BIOS boot target options are not configurable in Redfish; only UEFI boot targets are supported. PXE boot is an option by selecting the correct combination of bios attribute settings for the respective NIC and boot source target in the Boot object within @odata.type computersystem
