### ISSUE TITLE
NetworkInterface is not available on iLO 5

### ISSUE THREAD

**Issue by adrianlasota** [HewlettPackard/python-ilorest-library#99]
According to docs: https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#networkinterface-v1_1_1-networkinterface
I tried read NetworkInterface and NetworkPort, but in resources it isn't available
`{{iloURI}}/redfish/v1/Systems/1/NetworkAdapters`

```json
{
    "error": {
        "code": "iLO.0.10.ExtendedInfo",
        "message": "See @Message.ExtendedInfo for more information.",
        "@Message.ExtendedInfo": [
            {
                "MessageArgs": [
                    "/redfish/v1/Systems/1/NetworkAdapters"
                ],
                "MessageId": "Base.1.4.ResourceMissingAtURI"
            }
        ]
    }
}
```
in `/redfish/v1/Chassis/1/NetworkAdapters/` there is

```json
{
    "@odata.context": "/redfish/v1/$metadata#NetworkAdapterCollection.NetworkAdapterCollection",
    "@odata.etag": "W/\"F303ECE9\"",
    "@odata.id": "/redfish/v1/Chassis/1/NetworkAdapters/",
    "@odata.type": "#NetworkAdapterCollection.NetworkAdapterCollection",
    "Description": "The collection of network adapter resource instances available in this chassis.",
    "Name": "NetworkAdapterCollection",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeNetworkAdapterStatus.HpeNetworkAdapterStatus",
            "@odata.type": "#HpeNetworkAdapterStatus.v1_0_0.HpeNetworkAdapterStatus",
            "MemberContents": "AllDevices"
        }
    },
    "Members": [],
    "Members@odata.count": 0
}
```

**Comment by KeepSummerSaf3** [comment]
Use these collection URIs, (if you plan to use URIs):

- iLO Ethernet Management Interface NICs: /redfish/v1/Managers/1/EthernetInterfaces
- System NICs: /redfish/v1/Systems/1/EthernetInterfaces

Suggest referencing/mapping @odata.type, @odata.id 
(That being said, the types are not unique in this scenario, EthernetInterfaceCollection. ; however, they should be. That type will map to both, so then a filter is also suggested.)

**Comment by adrianlasota** [comment]
I'm going to use it. I'm looking for reading/changing settings configuration for network port. Could you help?
![image](https://user-images.githubusercontent.com/64520076/98206036-829f3180-1f39-11eb-94ff-a2c1d7b945db.png)

**Comment by KeepSummerSaf3** [comment]
Suggest to contact HPE support for your specific use case.

**Comment by rajeevkallur** [comment]
Please refer to the below link for ethernetinterfaces
https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#ethernetinterface-v1_4_1-ethernetinterface
